This notebooks takes data from various APIs and CSV files and combines for further analysis

In [173]:
import pandas as pd
import requests

# Getting the docking station locations from the Transport for London API

In [13]:
app_key = "Insert App Key here"

In [237]:
from tfl.client import Client
from tfl.api_token import ApiToken

app_id = 'Bike_exploration'


token = ApiToken(app_id, app_key)

client = Client(token)
print (client.get_line_meta_modes())
print (client.get_lines(mode="bus")[0])
print (client.get_lines(line_id="victoria")[0])

[<tfl.models.mode.Mode object at 0x000002917D0232B0>, <tfl.models.mode.Mode object at 0x000002917D0A3D00>, <tfl.models.mode.Mode object at 0x000002917D0A3C70>, <tfl.models.mode.Mode object at 0x000002917CE0DB50>, <tfl.models.mode.Mode object at 0x000002917CE0DAF0>, <tfl.models.mode.Mode object at 0x000002917CE0DC70>, <tfl.models.mode.Mode object at 0x000002917CE0D760>, <tfl.models.mode.Mode object at 0x000002917CE0D880>, <tfl.models.mode.Mode object at 0x000002917CE0D7F0>, <tfl.models.mode.Mode object at 0x000002917CE0D7C0>, <tfl.models.mode.Mode object at 0x000002917CE0D400>, <tfl.models.mode.Mode object at 0x000002917CE0D490>, <tfl.models.mode.Mode object at 0x000002917CE0DA60>, <tfl.models.mode.Mode object at 0x000002917CE0D2E0>, <tfl.models.mode.Mode object at 0x000002917CE0D250>, <tfl.models.mode.Mode object at 0x000002917CE0D1C0>, <tfl.models.mode.Mode object at 0x000002917CE0D160>, <tfl.models.mode.Mode object at 0x000002917CE0D100>]
{'additional_properties': {'$type': 'Tfl.Api.Presentation.Entities.Line, Tfl.Api.Presentation.Entities'}, 'id': '1', 'name': '1', 'mode_name': 'bus', 'disruptions': [], 'created': datetime.datetime(2021, 3, 2, 13, 59, 20, 160000, tzinfo=<isodate.tzinfo.Utc object at 0x000002917CE4B9D0>), 'modified': datetime.datetime(2021, 3, 2, 13, 59, 20, 160000, tzinfo=<isodate.tzinfo.Utc object at 0x000002917CE4B9D0>), 'line_statuses': [], 'route_sections': [], 'service_types': [<tfl.models.service_type.ServiceType object at 0x000002917CE0DC70>], 'crowding': <tfl.models.crowding.Crowding object at 0x000002917CE0DAF0>}
{'additional_properties': {'$type': 'Tfl.Api.Presentation.Entities.Line, Tfl.Api.Presentation.Entities'}, 'id': 'victoria', 'name': 'Victoria', 'mode_name': 'tube', 'disruptions': [], 'created': datetime.datetime(2021, 3, 2, 13, 59, 20, 130000, tzinfo=<isodate.tzinfo.Utc object at 0x000002917CE4B9D0>), 'modified': datetime.datetime(2021, 3, 2, 13, 59, 20, 130000, tzinfo=<isodate.tzinfo.Utc object at 0x000002917CE4B9D0>), 'line_statuses': [], 'route_sections': [], 'service_types': [<tfl.models.service_type.ServiceType object at 0x0000029175592790>, <tfl.models.service_type.ServiceType object at 0x00000291755921F0>], 'crowding': <tfl.models.crowding.Crowding object at 0x0000029175592490>}

In [221]:
from tfl.models import StopPoint
#using the tfl api to get all the docking station locations
url = "https://api.tfl.gov.uk/BikePoint/"
response = requests.get(url)

all_places = response.json()

In [225]:
all_places = pd.DataFrame(all_places)

*Exploring the results of the request*

In [226]:
all_places.head()

,$type,id,url,commonName,placeType,additionalProperties,children,childrenUrls,lat,lon
0,"Tfl.Api.Presentation.Entities.Place, Tfl.Api.P...",BikePoints_202,/Place/BikePoints_202,"Leman Street, Aldgate",BikePoint,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...,[],[],51.512363,-0.069542
1,"Tfl.Api.Presentation.Entities.Place, Tfl.Api.P...",BikePoints_203,/Place/BikePoints_203,"West Smithfield Rotunda, Farringdon",BikePoint,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...,[],[],51.518218,-0.100791
2,"Tfl.Api.Presentation.Entities.Place, Tfl.Api.P...",BikePoints_204,/Place/BikePoints_204,"Margery Street, Clerkenwell",BikePoint,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...,[],[],51.526599,-0.112432
3,"Tfl.Api.Presentation.Entities.Place, Tfl.Api.P...",BikePoints_206,/Place/BikePoints_206,"New Road 1 , Whitechapel",BikePoint,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...,[],[],51.518154,-0.062697
4,"Tfl.Api.Presentation.Entities.Place, Tfl.Api.P...",BikePoints_207,/Place/BikePoints_207,"Grosvenor Crescent, Belgravia",BikePoint,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...,[],[],51.501352,-0.153194

In [227]:
all_places["id"] = list(map(lambda x : x.replace("BikePoints_",""), all_places["id"]))

In [228]:
all_places["additionalProperties"][0]

[{'$type': 'Tfl.Api.Presentation.Entities.AdditionalProperties, Tfl.Api.Presentation.Entities',
  'category': 'Description',
  'key': 'TerminalName',
  'sourceSystemKey': 'BikePoints',
  'value': '001102',
  'modified': '2021-03-02T10:54:13.38Z'},
 {'$type': 'Tfl.Api.Presentation.Entities.AdditionalProperties, Tfl.Api.Presentation.Entities',
  'category': 'Description',
  'key': 'Installed',
  'sourceSystemKey': 'BikePoints',
  'value': 'true',
  'modified': '2021-03-02T10:54:13.38Z'},
 {'$type': 'Tfl.Api.Presentation.Entities.AdditionalProperties, Tfl.Api.Presentation.Entities',
  'category': 'Description',
  'key': 'Locked',
  'sourceSystemKey': 'BikePoints',
  'value': 'false',
  'modified': '2021-03-02T10:54:13.38Z'},
 {'$type': 'Tfl.Api.Presentation.Entities.AdditionalProperties, Tfl.Api.Presentation.Entities',
  'category': 'Description',
  'key': 'InstallDate',
  'sourceSystemKey': 'BikePoints',
  'value': '1279444320000',
  'modified': '2021-03-02T10:54:13.38Z'},
 {'$type': 'Tfl.Api.Presentation.Entities.AdditionalProperties, Tfl.Api.Presentation.Entities',
  'category': 'Description',
  'key': 'RemovalDate',
  'sourceSystemKey': 'BikePoints',
  'value': '',
  'modified': '2021-03-02T10:54:13.38Z'},
 {'$type': 'Tfl.Api.Presentation.Entities.AdditionalProperties, Tfl.Api.Presentation.Entities',
  'category': 'Description',
  'key': 'Temporary',
  'sourceSystemKey': 'BikePoints',
  'value': 'false',
  'modified': '2021-03-02T10:54:13.38Z'},
 {'$type': 'Tfl.Api.Presentation.Entities.AdditionalProperties, Tfl.Api.Presentation.Entities',
  'category': 'Description',
  'key': 'NbBikes',
  'sourceSystemKey': 'BikePoints',
  'value': '13',
  'modified': '2021-03-02T10:54:13.38Z'},
 {'$type': 'Tfl.Api.Presentation.Entities.AdditionalProperties, Tfl.Api.Presentation.Entities',
  'category': 'Description',
  'key': 'NbEmptyDocks',
  'sourceSystemKey': 'BikePoints',
  'value': '24',
  'modified': '2021-03-02T10:54:13.38Z'},
 {'$type': 'Tfl.Api.Presentation.Entities.AdditionalProperties, Tfl.Api.Presentation.Entities',
  'category': 'Description',
  'key': 'NbDocks',
  'sourceSystemKey': 'BikePoints',
  'value': '37',
  'modified': '2021-03-02T10:54:13.38Z'}]

In [229]:
all_places1 = all_places[["id", "commonName", "lat", "lon", "additionalProperties"]]

In [230]:
all_places1

,id,commonName,lat,lon,additionalProperties
0,202,"Leman Street, Aldgate",51.512363,-0.069542,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...
1,203,"West Smithfield Rotunda, Farringdon",51.518218,-0.100791,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...
2,204,"Margery Street, Clerkenwell",51.526599,-0.112432,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...
3,206,"New Road 1 , Whitechapel",51.518154,-0.062697,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...
4,207,"Grosvenor Crescent, Belgravia",51.501352,-0.153194,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...
...,...,...,...,...,...
787,814,"Clapham Road, Lingham Street, Stockwell",51.471433,-0.123670,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...
788,815,"Lambeth Palace Road, Waterloo",51.500089,-0.116628,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...
789,816,"Here East South, Queen Elizabeth Olympic Park",51.546532,-0.020597,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...
790,637,"Spencer Park, Wandsworth Common",51.457870,-0.174691,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...
791,277,"Kensington Church Street, Kensington",51.503157,-0.191496,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...

In [231]:
#find types of additional properties
properties = []
for i in range(9):
    properties.append(all_places1["additionalProperties"][0][i]["key"])

In [232]:
#create empty columns
for category in properties:
    all_places1[category] = ""

<ipython-input-232-1ba1e0308dae>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_places1[category] = ""

In [233]:
all_places1

,id,commonName,lat,lon,additionalProperties,TerminalName,Installed,Locked,InstallDate,RemovalDate,Temporary,NbBikes,NbEmptyDocks,NbDocks
0,202,"Leman Street, Aldgate",51.512363,-0.069542,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...,,,,,,,,,
1,203,"West Smithfield Rotunda, Farringdon",51.518218,-0.100791,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...,,,,,,,,,
2,204,"Margery Street, Clerkenwell",51.526599,-0.112432,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...,,,,,,,,,
3,206,"New Road 1 , Whitechapel",51.518154,-0.062697,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...,,,,,,,,,
4,207,"Grosvenor Crescent, Belgravia",51.501352,-0.153194,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
787,814,"Clapham Road, Lingham Street, Stockwell",51.471433,-0.123670,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...,,,,,,,,,
788,815,"Lambeth Palace Road, Waterloo",51.500089,-0.116628,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...,,,,,,,,,
789,816,"Here East South, Queen Elizabeth Olympic Park",51.546532,-0.020597,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...,,,,,,,,,
790,637,"Spencer Park, Wandsworth Common",51.457870,-0.174691,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...,,,,,,,,,
791,277,"Kensington Church Street, Kensington",51.503157,-0.191496,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...,,,,,,,,,

In [234]:
#expand additional properties into new columns
for j in range(all_places1.shape[0]):
    for i in range(len(properties)):
        all_places1.at[j, properties[i]] = all_places1["additionalProperties"][j][i]["value"]

In [235]:
all_places1=all_places1.drop(["additionalProperties"], axis=1)

In [236]:
all_places1.head()

,id,commonName,lat,lon,TerminalName,Installed,Locked,InstallDate,RemovalDate,Temporary,NbBikes,NbEmptyDocks,NbDocks
0,202,"Leman Street, Aldgate",51.512363,-0.069542,001102,true,false,1279444320000,,false,13,24,37
1,203,"West Smithfield Rotunda, Farringdon",51.518218,-0.100791,001040,true,false,1279445580000,,false,6,9,15
2,204,"Margery Street, Clerkenwell",51.526599,-0.112432,003468,true,false,1279466640000,,false,6,13,19
3,206,"New Road 1 , Whitechapel",51.518154,-0.062697,001171,true,false,1279471380000,,false,26,9,36
4,207,"Grosvenor Crescent, Belgravia",51.501352,-0.153194,001169,true,false,1279558140000,,false,12,6,18

In [238]:
all_places1.dtypes

id               object
commonName       object
lat             float64
lon             float64
TerminalName     object
Installed        object
Locked           object
InstallDate      object
RemovalDate      object
Temporary        object
NbBikes          object
NbEmptyDocks     object
NbDocks          object
dtype: object

In [241]:
all_places1["id"] = all_places1["id"].apply(lambda x : int(x))

In [278]:
all_places[all_places1["id"] == 111]

,$type,id,url,commonName,placeType,additionalProperties,children,childrenUrls,lat,lon
417,"Tfl.Api.Presentation.Entities.Place, Tfl.Api.P...",111,/Place/BikePoints_111,"Park Lane , Hyde Park",BikePoint,[{'$type': 'Tfl.Api.Presentation.Entities.Addi...,[],[],51.510017,-0.157275

In [243]:
all_places1.to_csv("all_bike_locations.csv")

# Exploring the journey data

*Importing one week of journeys*

In [222]:
data = pd.read_csv("234JourneyDataExtract30Sep2020-06Oct2020.csv")

In [223]:
data.head()

,Rental Id,Duration,Bike Id,End Date,EndStation Id,EndStation Name,Start Date,StartStation Id,StartStation Name
0,102520793,120,18474,01/10/2020 15:48,87,"Devonshire Square, Liverpool Street",01/10/2020 15:46,122,"Norton Folgate, Liverpool Street"
1,102562715,180,15093,03/10/2020 15:47,307,"Black Lion Gate, Kensington Gardens",03/10/2020 15:44,307,"Black Lion Gate, Kensington Gardens"
2,102545479,600,16646,02/10/2020 15:58,87,"Devonshire Square, Liverpool Street",02/10/2020 15:48,502,"Bonner Gate, Victoria Park"
3,102600590,300,15140,05/10/2020 16:57,502,"Bonner Gate, Victoria Park",05/10/2020 16:52,502,"Bonner Gate, Victoria Park"
4,102623002,960,1888,06/10/2020 13:37,502,"Bonner Gate, Victoria Park",06/10/2020 13:21,87,"Devonshire Square, Liverpool Street"

In [224]:
#for one week I have over 150,000 rows of data
data.shape

(158822, 9)

In [237]:
#check duration column. The times are given in seconds.
data["Duration"].value_counts()

480       8126
540       8084
420       7962
660       7756
600       7749
          ...
73440        1
140160       1
66660        1
25800        1
81960        1
Name: Duration, Length: 476, dtype: int64

In [239]:
data["EndStation Id"].value_counts()

194    895
132    789
154    681
74     681
191    664
      ...
560     29
472     27
44      22
608     18
494      9
Name: EndStation Id, Length: 787, dtype: int64

In [240]:
data["StartStation Id"].value_counts()

132    746
194    678
154    673
74     667
191    659
      ...
472     32
586     31
608     19
494      7
44       2
Name: StartStation Id, Length: 787, dtype: int64

*Finding the most popular single journey during this week*

In [263]:
mytable = data.groupby(['EndStation Id','StartStation Id']).size().reset_index().rename(columns={0:'count'})

In [264]:
mytable=pd.DataFrame(mytable)

In [265]:
mytable.columns

Index(['EndStation Id', 'StartStation Id', 'count'], dtype='object')

In [274]:
mytable.sort_values(by=['count'], inplace=True, ascending=False)

In [275]:
mytable

       EndStation Id  StartStation Id  count
73926            785              785    237
21019            191              191     89
11847            111              111     69
52439            530              530     56
50231            502              502     55
...              ...              ...    ...
9834              95              795      1
40122            368              224      1
40123            368              225      1
40124            368              228      1
39338            359                6      1

[78676 rows x 3 columns]

# Trying the Bing API to get local features

In [5]:
url = "http://dev.virtualearth.net/REST/v1/locationrecog/51.507244,-0.106237?key=KEY&output=json"

In [7]:
response = requests.get(url)

bing_place = response.json()

bing_place

{'authenticationResultCode': 'ValidCredentials',
 'brandLogoUri': 'http://dev.virtualearth.net/Branding/logo_powered_by.png',
 'copyright': 'Copyright © 2021 Microsoft and its suppliers. All rights reserved. This API cannot be accessed and the content and any results may not be used, reproduced or transmitted in any manner without express written permission from Microsoft Corporation.',
 'resourceSets': [{'estimatedTotal': 1,
   'resources': [{'__type': 'LocationRecog:http://schemas.microsoft.com/search/local/ws/rest/v1',
     'isPrivateResidence': 'false',
     'businessesAtLocation': [{'businessAddress': {'latitude': 51.5073602,
        'longitude': -0.1062147,
        'addressLine': '22 Stamford Street, Blackfriars',
        'adminDivision': 'London',
        'countryIso2': 'GB',
        'postalCode': 'SE1 9LJ',
        'formattedAddress': '22 Stamford Street, Blackfriars, SE1 9LJ'},
       'businessInfo': {'entityName': 'HSBC UK',
        'url': 'http://hsbc.co.uk/',
        'phone': '0845 740 4404',
        'type': 'Banks and Credit Unions',
        'otherTypes': ['Banking and Finance']}},
      {'businessAddress': {'latitude': 51.5071452365638,
        'longitude': -0.106217242389962,
        'addressLine': '1 Paris Garden, Battersea Park',
        'locality': 'London',
        'countryIso2': 'GB',
        'formattedAddress': '1 Paris Garden, Battersea Park, London'},
       'businessInfo': {'entityName': 'Scaramouche + Fandango',
        'url': 'http://scaramoucheandfandango.com/'}},
      {'businessAddress': {'latitude': 51.5071452365638,
        'longitude': -0.106217242389962,
        'addressLine': '1 Paris Garden, South Bank',
        'locality': 'London',
        'countryIso2': 'GB',
        'formattedAddress': '1 Paris Garden, South Bank, London'},
       'businessInfo': {'entityName': 'Resonate Interiors',
        'url': 'http://www.resonateinteriors.com/'}},
      {'businessAddress': {'latitude': 51.5071452365638,
        'longitude': -0.106217242389962,
        'addressLine': '1-2 Paris Garden, South Bank',
        'locality': 'London',
        'countryIso2': 'GB',
        'formattedAddress': '1-2 Paris Garden, South Bank, London'},
       'businessInfo': {'entityName': 'Fluxaxis',
        'url': 'http://www.fluxaxis.com/'}},
      {'businessAddress': {'latitude': 51.5071452365638,
        'longitude': -0.106217242389962,
        'addressLine': '1-2 Paris Garden, South Bank',
        'locality': 'London',
        'countryIso2': 'GB',
        'formattedAddress': '1-2 Paris Garden, South Bank, London'},
       'businessInfo': {'entityName': 'Halkin',
        'url': 'https://www.halkin.com/'}},
      {'businessAddress': {'latitude': 51.5071452365638,
        'longitude': -0.106217242389962,
        'addressLine': 'Bastille Court, 1-2 Paris Garden, South Bank',
        'locality': 'London',
        'countryIso2': 'GB',
        'formattedAddress': 'Bastille Court, 1-2 Paris Garden, South Bank, London'},
       'businessInfo': {'entityName': 'KBC Process Technology Ltd.',
        'url': 'http://www.kbcat.com/'}},
      {'businessAddress': {'latitude': 51.5071452365638,
        'longitude': -0.106217242389962,
        'addressLine': '1 Paris Garden, South Bank',
        'locality': 'London',
        'countryIso2': 'GB',
        'formattedAddress': '1 Paris Garden, South Bank, London'},
       'businessInfo': {'entityName': 'fdu',
        'url': 'http://www.fdu-group.com/'}},
      {'businessAddress': {'latitude': 51.50732,
        'longitude': -0.10605,
        'addressLine': '6 Milroy Walk',
        'locality': 'London',
        'adminDivision': 'Greater London',
        'countryIso2': 'GB',
        'postalCode': 'SE1 9LW',
        'formattedAddress': '6 Milroy Walk, London, SE1 9LW'},
       'businessInfo': {'entityName': 'Kings Sandwich Bar',
        'phone': '020 7633 9115',
        'type': 'Bars',
        'otherTypes': ['Food and Drink', 'EatDrink']}},
      {'businessAddress': {'latitude': 51.5073602,
        'longitude': -0.1062147,
        'addressLine': '22 Stamford St, Blackfriars',
        'locality': 'London',
        'adminDivision': 'Greater London',
        'countryIso2': 'GB',
        'postalCode': 'SE1 9LJ',
        'formattedAddress': '22 Stamford St, Blackfriars, London, SE1 9LJ'},
       'businessInfo': {'entityName': 'Momentum Transport',
        'phone': '0800 698 0209',
        'type': 'Buses and Charters',
        'otherTypes': ['Ground Transportation', 'Travel']}},
      {'businessAddress': {'latitude': 51.50732,
        'longitude': -0.10605,
        'addressLine': '5 Milroy Walk',
        'locality': 'London',
        'adminDivision': 'Greater London',
        'countryIso2': 'GB',
        'postalCode': 'SE1 9LW',
        'formattedAddress': '5 Milroy Walk, London, SE1 9LW'},
       'businessInfo': {'entityName': 'Milroy Foodfayre',
        'phone': '020 7633 9401',
        'type': 'Grocery',
        'otherTypes': ['Supermarkets', 'Retail', 'EatDrink']}}],
     'naturalPOIAtLocation': [],
     'addressOfLocation': []}]}],
 'statusCode': 200,
 'statusDescription': 'OK',
 'traceId': 'ad492f91dc8e42d598dd61fcd6c7d88c|DU00000B76|0.0.0.1'}

# Trying Geocoder

*The aim is to find the borough and postcode of each docking station to then connect with other data sources*

In [19]:
import geocoder

g = geocoder.osm([51.50732, -0.10605], method='reverse')
g.json["district"]

'London Borough of Southwark'

In [23]:
bike_locations = pd.read_csv("all_bike_locations.csv")

In [71]:
bike_locations.head()

,ID,commonName,lat,lon,TerminalName,Installed,Locked,InstallDate,RemovalDate,Temporary,NbBikes,NbEmptyDocks,NbDocks,borough
0,195,"Milroy Walk, South Bank",51.507244,-0.106237,959,True,False,1.280000e+12,NaN,False,5,25,30,London Borough of Southwark
1,194,"Hop Exchange, The Borough",51.504627,-0.091773,960,True,False,1.280000e+12,NaN,False,18,38,56,London Borough of Southwark
2,196,"Union Street, The Borough",51.503688,-0.098497,961,True,False,1.280000e+12,NaN,False,10,7,17,London Borough of Southwark
3,197,"Stamford Street, South Bank",51.505569,-0.111606,962,True,False,1.280000e+12,NaN,False,21,6,27,London Borough of Lambeth
4,193,"Bankside Mix, Bankside",51.505817,-0.100186,963,True,False,1.280000e+12,NaN,False,46,14,60,London Borough of Southwark

In [72]:
bike_locations["postcode"]=""

In [77]:
#example output from geocoder
i=7
lat = bike_locations.at[i, "lat"]
lon = bike_locations.at[i, "lon"]
g=geocoder.osm([lat, lon], method='reverse')
g.json

{'accuracy': 0.001,
 'address': 'New Kent Road, Harper Road, Borough, Walworth, London Borough of Southwark, London, Greater London, England, SE17, United Kingdom',
 'bbox': {'northeast': [51.4944015, -0.0928758],
  'southwest': [51.4943015, -0.0929758]},
 'city': 'London',
 'confidence': 10,
 'country': 'United Kingdom',
 'country_code': 'gb',
 'district': 'London Borough of Southwark',
 'importance': 0.001,
 'lat': 51.4943515,
 'lng': -0.0929258,
 'ok': True,
 'osm_id': 855682685,
 'osm_type': 'node',
 'place_id': 7404594,
 'place_rank': 30,
 'postal': 'SE17',
 'quality': 'bicycle_rental',
 'quarter': 'Borough',
 'raw': {'place_id': 7404594,
  'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'node',
  'osm_id': 855682685,
  'boundingbox': ['51.4943015', '51.4944015', '-0.0929758', '-0.0928758'],
  'lat': '51.4943515',
  'lon': '-0.0929258',
  'display_name': 'New Kent Road, Harper Road, Borough, Walworth, London Borough of Southwark, London, Greater London, England, SE17, United Kingdom',
  'place_rank': 30,
  'category': 'amenity',
  'type': 'bicycle_rental',
  'importance': 0.001,
  'address': {'amenity': 'New Kent Road',
   'road': 'Harper Road',
   'quarter': 'Borough',
   'suburb': 'Walworth',
   'city_district': 'London Borough of Southwark',
   'city': 'London',
   'state_district': 'Greater London',
   'state': 'England',
   'postcode': 'SE17',
   'country': 'United Kingdom',
   'country_code': 'gb'}},
 'region': 'England',
 'state': 'England',
 'status': 'OK',
 'street': 'Harper Road',
 'suburb': 'Walworth',
 'type': 'bicycle_rental'}

In [73]:
import time

for i in range(bike_locations.shape[0]):
    
    lat = bike_locations.at[i, "lat"]
    lon = bike_locations.at[i, "lon"]
    g=geocoder.osm([lat, lon], method='reverse')
    try:
        bike_locations.at[i, "postcode"] = g.json["raw"]["address"]["postcode"]
    except KeyError:
            print (bike_locations.at[i, "commonName"], "no postcode")
            
    #time.sleep(1) # Seconds

Devonshire Square, Liverpool Street no postcode
Podium, Queen Elizabeth Olympic Park no postcode

In [98]:
bike_locations["postcode"].value_counts()

SE1 0HX     3
SE1 8XR     3
SW7 5QL     3
            2
WC2A 2AE    2
           ..
SW3 2LX     1
SE1 7TY     1
W14 8DE     1
NW1 0JA     1
E8 4PN      1
Name: postcode, Length: 765, dtype: int64

# Web Scraping checkmypostcode.co.uk to find more local information

In [103]:
#scraping check my postcode
url = "https://checkmypostcode.uk/w85se"
response = requests.get(url)

In [107]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')
soup

<!DOCTYPE HTML>

<html>
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<script src="/cdn-cgi/apps/head/18DOcyGOmT8PDnkkBnDwX7dWXK4.js"></script><link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css"/>
<link href="https://fonts.googleapis.com/css?family=Shadows+Into+Light" rel="stylesheet" type="text/css"/>
<link href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.4.1/jquery.fancybox.min.css" rel="stylesheet">
<link href="/css/foundation.css" rel="stylesheet">
<link href="/css/site.css" rel="stylesheet"/>
<link href="/css/sitenav.css" rel="stylesheet"/>
<link href="/css/foundation-icons.css" rel="stylesheet"/>
<script src="/js/vendor/jquery.js"></script>
<title>W8 5SE - Check My Postcode</title>
<meta content="IE=Edge" http-equiv="X-UA-Compatible"/>
<meta content="text/html;charset=utf-8" http-equiv="Content-Type"/>
<meta content="W8 5SE is a non-residential postcode in Kensington and Chelsea. Check typical house prices, council tax bands, business rates, broadband availability and local schools. Find nearby hotels and holiday rentals. " name="description"/>
<meta content="Good Stuff" name="author"/>
<meta content="#bfd255" name="theme-color"/>
<meta content="postcode" name="foo"/>
<link href="https://checkmypostcode.uk/w85se" rel="canonical"/>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('require', 'displayfeatures');
  ga('create', 'UA-25123446-47', 'auto');
  ga('send', 'pageview');

var trackOutboundLink = function(url,type) {
   ga('send', 'event', 'outbound', type, url, {'hitCallback':
     function () {
     	     //
     }
   });
}

</script>
<script async="" src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-8138990502704272",
    enable_page_level_ads: true
  });
</script>
</link></link></head>
<body>
<form action="/search/" method="get">
<div>
<nav class="top-bar" data-topbar="">
<ul class="title-area">
<li class="name">
<h1><a href="/" title="Check My Postcode"><i class="fi-home"></i></a></h1>
</li>
<li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
</ul>
<section class="top-bar-section">
<!-- Right Nav Section -->
<ul class="right">
<li class="has-dropdown">
<a href="/page/about">Help and Information</a>
<ul class="dropdown">
<li><a href="/page/about">About this website</a></li>
<li><a href="/page/privacy">Privacy Policy</a></li>
</ul>
</li>
</ul>
<!-- Left Nav Section -->
<ul class="left">
<li class="has-form">
<div class="row collapse">
<div class="large-8 small-9 columns">
<input name="q" placeholder="Postcode or place name" type="text"/>
</div>
<div class="large-4 small-3 columns">
<input class="button" type="submit" value="Search">
</input></div>
</div>
</li>
<li class="has-dropdown">
<a href="/counties">Postcode Lists</a>
<ul class="dropdown">
<li><a href="/counties/">By County</a></li>
<li><a href="/date/">By Introduction Date</a></li>
</ul>
</li>
<li class="has-dropdown">
<a href="/map">Postcode Maps</a>
<ul class="dropdown">
<li><a href="/map">User Type</a></li>
<li><a href="/map/use">Use Category</a></li>
<li><a href="/map/counciltax">Council Tax Band</a></li>
</ul>
</li>
<li>
<a href="/mypostcode/">Nearest Postcodes</a>
</li>
<li><a href="/postcode-lottery">Postcode Lottery</a></li>
</ul>
</section>
</nav>
</div>
</form>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.4.1/jquery.fancybox.min.js"></script>
<div class="row">
<div class="medium-12 columns">
<div data-magellan-expedition="fixed">
<dl class="sub-nav">
<dd data-magellan-arrival="top"><a href="#top">Top</a></dd>
<dd data-magellan-arrival="map"><a href="#map">Map</a></dd>
<dd data-magellan-arrival="summary"><a href="#summary">Summary</a></dd>
<dd data-magellan-arrival="reps"><a href="#reps">Elected representatives</a></dd>
<dd data-magellan-arrival="broadband"><a href="#broadband">Broadband</a></dd>
<dd data-magellan-arrival="schools"><a href="#schools">Schools</a></dd>
<dd data-magellan-arrival="comments"><a href="#comments">Comments</a></dd>
</dl>
</div>
</div>
</div>
<a data-magellan-destination="top" name="top"></a>
<span itemscope="" itemtype="http://schema.org/Article">
<div class="row">
<div class="medium-9 columns">
<h1 itemprop="name">W8 5SE</h1>
<h3>a non-residential postcode in Kensington and Chelsea</h3>
</div>
<div class="medium-3 columns">
<script src="https://www.britishbeaches.uk/js/beach-holidays.js?t=1614974244"></script>
</div>
</div>
<span itemprop="articleBody">
<a data-magellan-destination="map" name="map"></a>
<div class="row">
<div class="medium-6 columns">
<div id="map" style="height:330px;width:100%;text-align:center;border:1px solid black;">W8 5SE Location Map</div>
</div>
<div class="medium-6 columns">
<h3>Coordinates</h3>
<p class="flat nopad small">Latitude: 51.5016 / 51°30'5"N</p>
<p class="flat nopad small">Longitude: -0.1911 / 0°11'27"W</p>
<p class="flat nopad small">OS Eastings: 525652</p>
<p class="flat nopad small">OS Northings: 179627</p>
<p class="flat nopad small">OS Grid: TQ256796</p>
<h3>Location Encoding</h3>
<p class="flat nopad small">Mapcode National: GBR 1H.9W</p>
<p class="flat nopad small">Mapcode Global: VHGQY.MJT6</p>
<p class="flat nopad small">Plus Code: 9C3XGR25+JH</p>
<p class="flat nopad small">Maidenhead Locator System: IO91vm70</p>
<p class="flat nopad small">What Three Birds: redpoll.nutcracker.bullfinch</p>
<p>
<a href="/page/location-codes/">What are these?</a>
</p>
</div>
</div>
<div class="row">
<div class="medium-12 columns">
<p class="small"><em>
		Marker point and cooordinate accuracy: Within the building of the matched address closest to the postcode mean.
		</em></p>
<p>
<strong>Can you <a href="/where-is-w85se">answer a question about W8 5SE?</a></strong>
</p>
</div>
</div>
<div class="row">
<div class="medium-12 columns">
<p class="flat">
			W8 5SE is currently in Coronavirus (Covid-19)
			<span style="background:; color:; padding: 1px 4px 1px 4px"><strong>National Lockdown</strong></span>
</p>
<p class="flat small">
<em>Data from NHSX, correct as of 5 March 2021</em>
</p>
</div>
</div>
<a data-magellan-destination="summary" name="summary"></a>
<div class="row spaced">
<div class="medium-12 columns panel">
<h4>Kensington High Street, London W8 5SE</h4> </div>
</div>
<div class="row">
<div class="medium-6 columns">
<h4 class="infotitle">Summary</h4>
<p>
		W8 5SE is a non-residential postcode in Kensington and Chelsea.
					It was first introduced in January 1980.
					</p>
<p>
				Commercial rateable values range from £144 to
				£1,670,000 with an average of £835,072.
								The most common recorded business types are Shop and
				Bicycle Docking Station.

			</p>
<p>
			W8 5SE is in the London travel to work area. NHS services are provided by the
			Kensington and Chelsea Primary Care Trust.
			</p>
<p>
							W8 5SE is approximately 27m (89ft) above sea level.
							</p>
<p><a data-reveal-id="br_list" href="#">See all rateable values in W8 5SE</a></p>
<div aria-hidden="true" aria-labelledby="modalTitle" class="reveal-modal" data-reveal="" id="br_list" role="dialog">
<h3>All rateable values in W8 5SE</h3>
<table>
<tr><th>Address</th><th>Type</th><th>Rateable Value</th></tr>
<tr><td>12/611233, Derry Street, London</td><td>Bicycle Docking Station &amp; Premises</td><td class="text-right">£144</td></tr>
<tr><td>63-97, Kensington High Street, London</td><td>Shop</td><td class="text-right">£1,930,000</td></tr>
</table>
<a aria-label="Close" class="close-reveal-modal">×</a>
</div>
<div class="row">
<a href="https://www.booking.com/searchresults.html?city=-2607607&amp;aid=1353860&amp;label=cmp">
<div class="medium-12 columns">
<div class="row">
<div class="medium-12 columns bcbluebox text-center">
<h3>Find hotels near W8 5SE</h3>
</div>
</div>
<div class="row">
<div class="medium-12 columns bcbluebox text-center">
<img src="/img/bc-blue.jpg"/>
</div>
</div>
</div>
</a>
</div>
</div>
<div class="medium-6 columns">
<p class="infotitle">
			Office of National Statistics Output Area Classification for the area containing W8 5SE</p>
<p>
			2a1: Cosmopolitans - Students Around Campus - Student Communal Living			</p>
<p class="infotitle">
			Office of National Statistics Rural/Urban classification for W8 5SE</p>
<p>
			England A1: within a very large conurbation, surrounded by populated countryside			</p>
<p class="infotitle">Healthy Living Index</p>
<p>
			10/10 (Very high)
			</p>
<p class="infotitle">Neighbourhood Retail Diversity Index</p>
<p>
			10/10 (Very high)
			</p>
<p class="infotitle">Area Retail Diversity Index</p>
<p>
			10/10 (Very high)
			</p>
<p>
				Supermarkets near W8 5SE include Aldi, Asda, Budgens, Co-Operative Food, Costcutter, Iceland, Lidl, Waitrose, Londis, M&amp;S Simply Food, Sainsbury's and Tesco. <em>(Source: Open Streetmap)</em>
</p>
<h4 class="infotitle">Other nearby postcodes</h4>
<ul>
<li><a href="/w85ee">Derry Street W8 5EE</a></li>
<li><a href="/w85hf">Derry Street W8 5HF</a></li>
<li><a href="/w85tt">Derry Street W8 5TT</a></li>
<li><a href="/w85ts">Derry Street W8 5TS</a></li>
<li><a href="/w85hy">Derry Street W8 5HY</a></li>
<li><a href="/w84sp">Kensington Church Court W8 4SP</a></li>
<li><a href="/w84sh">Kensington High Street W8 4SH</a></li>
<li><a href="/w84sg">Kensington High Street W8 4SG</a></li>
<li><a href="/w85sa">Kensington High Street W8 5SA</a></li>
<li><a href="/w85hr">Kensington Square W8 5HR</a></li>
</ul>
<p>
<a href="/greater-london/kensington-and-chelsea">See all postcodes in Kensington and Chelsea</a>
</p>
</div>
</div>
<div class="row">
<div class="medium-9 columns panel callout">
<h4>W8 5SE at other websites</h4>
<div class="twocol spaced">
<ul class="no-bullet">
<li>
<a href="https://smogwatch.co.uk/postcode/W8+5SE" onclick="trackOutboundLink('https://smogwatch.co.uk/postcode/W8+5SE','Smogwatch'); return true;" target="_blank">Air quality forecast for W8 5SE</a> at Smogwatch				</li>
<li>
<a href="https://www.thetimeandplace.info/uk/postcode/W8+5SE" onclick="trackOutboundLink('https://www.thetimeandplace.info/uk/postcode/W8+5SE','The Time and Place'); return true;" target="_blank">Sunrise and sunset times at W8 5SE</a> at The Time and Place				</li>
<li>
<a href="https://riverlevels.uk/search/?q=W8+5SE" onclick="trackOutboundLink('https://riverlevels.uk/search/?q=W8+5SE','River Levels UK'); return true;" target="_blank">River levels and flood warnings near W8 5SE</a> at River Levels UK				</li>
<li>
<a href="https://www.britishlistedbuildings.co.uk/search/?q=W8+5SE" onclick="trackOutboundLink('https://www.britishlistedbuildings.co.uk/search/?q=W8+5SE','British Listed Buildings'); return true;" target="_blank">Listed Buildings near W8 5SE</a> at British Listed Buildings				</li>
<li>
<a href="https://hygieneratings.uk/w85se" onclick="trackOutboundLink('https://hygieneratings.uk/w85se','Hygiene Ratings UK'); return true;" target="_blank">Food Hygiene Ratings near W8 5SE</a> at Hygiene Ratings UK				</li>
<li>
<a href="https://britishbeaches.uk/search/?q=W8+5SE" onclick="trackOutboundLink('https://britishbeaches.uk/search/?q=W8+5SE','British Beaches'); return true;" target="_blank">Nearest beaches to W8 5SE</a> at British Beaches				</li>
<li>
<a href="https://plugpoint.uk/postcode/w85se" onclick="trackOutboundLink('https://plugpoint.uk/postcode/w85se','Plugpoint'); return true;" target="_blank">Electric vehicle charge points near W8 5SE</a> at Plugpoint				</li>
<li>
<a href="https://repetition.me/search/?q=w85se" onclick="trackOutboundLink('https://repetition.me/search/?q=w85se','Repetition.me'); return true;" target="_blank">See which government petitions are popular near W8 5SE</a> at Repetition.me				</li>
<li>
<a href="https://uprn.uk/postcode/w85se" onclick="trackOutboundLink('https://uprn.uk/postcode/w85se','UPRN Data UK'); return true;" target="_blank">Unique Property Reference Numbers (UPRNs) near W8 5SE</a> at UPRN Data UK				</li>
</ul>
</div>
<p>(Links open in a new window)</p>
</div>
<div class="medium-3 columns">
<a href="https://www.amazon.co.uk/Map-Marketing-Postcode-Unframed-W830xH1200mm/dp/B000SHRHEC/ref=as_li_ss_il?ie=UTF8&amp;qid=1531235281&amp;sr=8-3&amp;keywords=postcode&amp;linkCode=li3&amp;tag=cmp-books-21&amp;linkId=56f9ab489e8a412dc3eed798ee78631f" rel="nofollow" target="_blank"><img alt="Postcode Map" border="0" src="//ws-eu.amazon-adsystem.com/widgets/q?_encoding=UTF8&amp;ASIN=B000SHRHEC&amp;Format=_SL250_&amp;ID=AsinImage&amp;MarketPlace=GB&amp;ServiceVersion=20070822&amp;WS=1&amp;tag=cmp-books-21" title="Postcode Map"/></a><img alt="" border="0" height="1" src="https://ir-uk.amazon-adsystem.com/e/ir?t=cmp-books-21&amp;l=li3&amp;o=2&amp;a=B000SHRHEC" style="border:none !important; margin:0px !important;" width="1">
</img></div>
</div>
<a data-magellan-destination="reps" name="reps"></a>
<div class="row panel tbox">
<div class="medium-12 columns">
<h4>Councils, constituencies and elected representatives</h4>
<p>
		Residents of W8 5SE are represented at different levels of local, regional and national government
		by elected representatives. Where known, these are shown here.
		</p>
<p>
<em>This data is updated approximately monthly, and may not necessarily take account of the results of any
		elections held recently.</em>
</p>
</div>
</div>
<div class="row borderb">
<div class="medium-4 columns">
<p class="infotitle">London Borough</p>
<p>Kensington and Chelsea Borough Council</p>
</div>
<div class="medium-4 columns">
<p class="infotitle">Ward</p>
<p>Queen's Gate</p>
</div>
<div class="medium-4 columns">
<p class="infotitle">Councillors</p>
<p>Max Chauhan (Conservative)<br/>Maxwell Woodger (Conservative)<br/>Matthew Palmer (Ideal Bradford)</p>
</div>
</div>
<div class="row border">
<div class="medium-4 columns">
<p class="infotitle">London Assembly</p>
</div>
<div class="medium-4 columns">
<p class="infotitle">London Assembly constituency</p>
<p>West Central</p>
</div>
<div class="medium-4 columns">
<p class="infotitle">Assembly Member</p>
<p>Tony Devenish (Conservative)</p>
</div>
</div>
<div class="row borderb">
<div class="medium-12 columns">
<p>
					The London Assembly also has eleven London-wide members elected via the d'Hondt (party list) system. These are not shown here.					</p>
</div>
</div>
<div class="row borderb">
<div class="medium-4 columns">
<p class="infotitle">United Kingdom Parliament</p>
</div>
<div class="medium-4 columns">
<p class="infotitle">Constituency</p>
<p>Kensington</p>
</div>
<div class="medium-4 columns">
<p class="infotitle">MP</p>
<p>
					Felicity Buchan (Conservative)					</p>
</div>
</div>
<div class="row">
<div class="medium-12 columns">
<a href="https://www.writetothem.com/who?pc=W8+5SE" target="_wtt">Contact your local representatives at WriteToThem.com</a>
			(link opens in a new tab)
			</div>
</div>
<a data-magellan-destination="broadband" name="broadband"></a>
<div class="row panel tbox">
<div class="medium-12 columns">
<h4>Broadband Internet</h4>
<p>
			Ofcom publishes annual statistics for Broadband availability. This is the most recent data
			for W8 5SE.
			</p>
</div>
</div>
<div class="row">
<div class="medium-6 columns">
<div style="padding:0 5px 0 5px">
<div class="row borderb">
<div class="medium-9 columns infotitle plike">
						Full fibre availability
						</div>
<div class="medium-3 columns plike text-right">
						%
						</div>
</div>
<div class="row borderb">
<div class="medium-9 columns infotitle plike">
						Ultrafast broadband availability
						</div>
<div class="medium-3 columns plike text-right">
						0%
						</div>
</div>
<div class="row borderb">
<div class="medium-9 columns infotitle plike">
						Superfast broadband availability
						</div>
<div class="medium-3 columns plike text-right">
						0%
						</div>
</div>
</div>
</div>
<div class="medium-6 columns">
<div style="padding:0 5px 0 5px">
<div class="row borderb">
<div class="medium-9 columns infotitle plike">
						Premises unable to receive 30Mbits/s
						</div>
<div class="medium-3 columns plike text-right">
						100%
					</div>
</div>
<div class="row borderb">
<div class="medium-9 columns infotitle plike">
						Premises unable to receive 10Mbits/s
						</div>
<div class="medium-3 columns plike text-right">
						0%
					</div>
</div>
<div class="row borderb">
<div class="medium-9 columns infotitle plike">
						Premises unable to receive 5Mbits/s
						</div>
<div class="medium-3 columns plike text-right">
						0%
					</div>
</div>
<div class="row borderb">
<div class="medium-9 columns infotitle plike">
						Premises unable to receive 2Mbits/s
						</div>
<div class="medium-3 columns plike text-right">
						0%
					</div>
</div>
<div class="row borderb">
<div class="medium-9 columns infotitle plike">
						Premises below Universal Service Obligation
						</div>
<div class="medium-3 columns plike text-right">
						0%
					</div>
</div>
</div>
</div>
</div>
<div class="row">
<div class="medium-12 columns">
<ul class="no-bullet">
<li><strong>Definitions</strong>
<li>Ultrafast: 300Mbit/s or greater </li>
<li>Superfast: 30Mbit/s to less than 300Mbit/s</li>
<li>Universal Service Obligation: Download speeds at or above 10Mbit/s and upload speeds at or above 1Mbit/s</li>
</li></ul>
</div>
</div>
<div class="row">
<div class="medium-12 columns">
<p>
				Broadband statistics for commercial properties are less reliable than for domestic properties, as
				businesses are more likely to have other forms of Internet access that are not classified as 'Broadband'.
				</p>
</div>
</div>
<div class="row spaced show for medium-up">
<div class="medium-12 columns text-center">
<script type="text/javascript"><!--
				amazon_ad_tag = "goodstuff03-21"; amazon_ad_width = "728"; amazon_ad_height = "90"; amazon_ad_logo = "hide"; amazon_ad_link_target = "new"; amazon_ad_border = "hide";//--></script>
<script src="https://ir-uk.amazon-adsystem.com/s/ads.js" type="text/javascript"></script>
</div>
</div>
<a data-magellan-destination="schools" name="schools"></a>
<div class="row panel tbox">
<div class="medium-12 columns">
<h4>Schools</h4>
<p>
			The most recent Ofsted rankings for schools near W8 5SE.
			</p>
</div>
</div>
<div class="row">
<div class="medium-12 columns">
<h4 class="infotitle">Primary</h4>
</div>
</div>
<div class="row borderb nopad">
<div class="medium-6 columns">
<p class="school flat">St Mary Abbots CofE Primary School</p>
<p class="flat">2 Kensington Church Court, Kensington, London,  <a href="/w84sp">W8 4SP</a></p>
</div>
<div class="medium-3 columns">
<p class="flat">Voluntary Aided School</p>
<p class="flat">Ages 5 - 11</p>
</div>
<div class="medium-3 columns">
<p class="flat">Good					</p></div>
</div>
<div class="row borderb nopad">
<div class="medium-6 columns">
<p class="school flat">St Barnabas and St Philip's CofE Primary School</p>
<p class="flat">58 Earls Court Road, Kensington, London,  <a href="/w86ej">W8 6EJ</a></p>
</div>
<div class="medium-3 columns">
<p class="flat">Voluntary Aided School</p>
<p class="flat">Ages 5 - 11</p>
</div>
<div class="medium-3 columns">
<p class="flat">Outstanding					</p></div>
</div>
<div class="row borderb nopad">
<div class="medium-6 columns">
<p class="school flat">Fox Primary School</p>
<p class="flat">Kensington Place, London,  <a href="/w87pp">W8 7PP</a></p>
</div>
<div class="medium-3 columns">
<p class="flat">Community School</p>
<p class="flat">Ages 4 - 11</p>
</div>
<div class="medium-3 columns">
<p class="flat">Outstanding					</p></div>
</div>
<div class="row borderb nopad">
<div class="medium-6 columns">

In [108]:
#trying to find the part of the website that describes whether the area is residential or non-residential
soup.select(selector)

In [110]:
soup.find_all("h3")[0]

In [111]:
bike_locations["description"] = ""

In [118]:
#adding the local information to the dataframe
print (bike_locations.shape[0])
for i in range(bike_locations.shape[0]):
    postcode = bike_locations.at[i, "postcode"].replace(" ", "")
    print(postcode)
    url = "https://checkmypostcode.uk/"+postcode
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    bike_locations.at[i, "description"] = soup.select("body > span:nth-child(5) > div:nth-child(1) > div:nth-child(1) > h3:nth-child(2)")
    time.sleep(1) # Seconds
    print (i, response.status_code)

792
SE19NN
0 200
SE11XF
1 200
SE10LN
2 200
SE19NQ
3 200
SE10HX
4 200
EC1V9ES
5 200
SW1V2LZ
6 200
SE16AJ
7 200
EC2Y8NQ
8 200
SW1E5BY
9 200
W1T2SF
10 200
EC4V5BD
11 200
NW12PY
12 200
E16LA
13 200
WC1N1EH
14 200
WC1X8SF
15 200
NW13NY
16 200
WC1N1JE
17 200
N17TA
18 200
WC1E7JN
19 200
WC1B5BH
20 200
EC1N2QX
21 200
NW12FB
22 200
EC2M5PG
23 200
EC1N8DX
24 200
EC1V4NN
25 200
WC1B3BQ
26 200
N1
27 404
SE114RH
28 200
EC3N2PH
29 200
EC1V7NH
30 200
NW12ET
31 200
SE13JB
32 200
W1F7TU
33 200
SE11QN
34 200
EC2A2BA
35 200
SE116PX
36 200
EC4R1BR
37 200
SW82FH
38 200
SW59QN
39 200
SW32BQ
40 200
W1G0BG
41 200
NW11LH
42 200
NW11DD
43 200
WC1B3HA
44 200
WC2B5AD
45 200
EC1N8DX
46 200
WC1H0BT
47 200
WC1N1AL
48 200
WC1H8AB
49 200
EC2A2BS
50 200
WC1H8BD
51 200
SE19AR
52 200
W24PS
53 200
SE14YF
54 200
W86SA
55 200
WC1X8EB
56 200
EC2A4LT
57 200
EC4Y8AX
58 200
WC1N1LZ
59 200
EC1R1XL
60 200
SE19EQ
61 200
W1W5JL
62 200
EC1Y0UA
63 200
W91AB
64 200
WC2N5LR
65 200
N17TG
66 200
NW89HJ
67 200
E1W1YY
68 200
EC2A3EA
69 200
W1U4EG
70 200
W1J6QB
71 200
NW16ER
72 200
W1U6AZ
73 200
W1K7TT
74 200
NW17FB
75 200
E1W1UJ
76 200
EC1A9DS
77 200
W24UA
78 200
W1C2AD
79 200
EC2Y5HN
80 200
EC2V7RF
81 200
EC3N1RE
82 200
SW1V3JL
83 200
N16NE
84 200
EC4V4BJ
85 200
EC1V8BU
86 200
NW14RB
87 200
N15DX
88 200
W1D3QJ
89 200
EC1R0DE
90 200
N17RE
91 200
NW8
92 404
EC2A1DX
93 200
EC1R4RG
94 200
NW15DH
95 200
SE17TY
96 200
EC1V1NQ
97 200
EC4A4AP
98 200
E18QS
99 200
EC2Y5AS
100 200
EC1V9FR
101 200
EC1A4JR
102 200
N19DA
103 200
SW1Y4PD
104 200
E16DB
105 200
SW1X8BS
106 200
SE14TD
107 200
EC3N4DR
108 200
SE17LY
109 200
SE114QA
110 200
EC1
111 404
SW1X7NL
112 200
SE116RB
113 200
E11BB
114 200
SE17JP
115 200
WC1H0EB
116 200
EC3M1HD
117 200
N10RP
118 200
SE10AQ
119 200
E16AZ
120 200
EC2A2AW
121 200
W1H7AN
122 200
W1U8EW
123 200
SW1V1QF
124 200
W22AR
125 200
SW75LE
126 200
W1T5BA
127 200
NW87RN
128 200
EC2M6XQ
129 200
SE115UQ
130 200
W85RY
131 200
SE10AE
132 200
W22ND
133 200
WC2N5AQ
134 200
EC3R6EN
135 200
W21AH
136 200
WC2R1EA
137 200
SW1X7NL
138 200
E18EY
139 200
SW1V2BA
140 200
N19LX
141 200
SW1V2JA
142 200
SW74QH
143 200
W21LA
144 200
W1J7NS
145 200
SW75ED
146 200
SE17NA
147 200
W1H5YN
148 200
SW59TD
149 200
SW1X9SH
150 200
W86LU
151 200
SW74ES
152 200
SE17XG
153 200
SE173DQ
154 200
W112QX
155 200
W85JT
156 200
SW1P1BX
157 200
WC1A2BP
158 200
SW73NT
159 200
W1F7HU
160 200
W1K6RS
161 200
N19QB
162 200
N16JB
163 200
NW89BS
164 200
N18BN
165 200
W1K7TT
166 200
SE17AU
167 200
W148QZ
168 200
SW1V3BQ
169 200
NW14RY
170 200
SE14HA
171 200
SW1W9UD
172 200
WC2A2JB
173 200
SW1V3BQ
174 200
WC2B6UF
175 200
SE12UD
176 200
W84LL
177 200
SE19UF
178 200
WC1A1BS
179 200
EC1R4RR
180 200
W9
181 404
SW1V1EJ
182 200
W24RH
183 200
WC2N5DG
184 200
W1C2JG
185 200
SW1Y5BL
186 200
SE116SF
187 200
SW1P4AW
188 200
NW12BF
189 200
W24RJ
190 200
WC2N5DN
191 200
EC1M6BQ
192 200
WC2N5HR
193 200
EC2M4QH
194 200
NW16QN
195 200
W1D6QB
196 200
W1B1NJ
197 200
SW118AU
198 200
NW1
199 404
W21RN
200 200
SW1X7EE
201 200
SW1P4DR
202 200
E11HE
203 200
SW75LP
204 200
W26HU
205 200
SW1V3EJ
206 200
NW88TA
207 200
SE18TX
208 200
SW1X7RQ
209 200
W26DE
210 200
SW33QT
211 200
SW1W8UN
212 200
W24EA
213 200
SW59AQ
214 200
EC3A8AL
215 200
SE18XR
216 200
NW88UL
217 200
NW17SN
218 200
SE14XE
219 200
SW81SU
220 200
EC2Y8DX
221 200
WC2E7AE
222 200
SW72QU
223 200
NW15JP
224 200
SW1V3AT
225 200
SW1P1LQ
226 200
W1S3DA
227 200
NW14QG
228 200
SE16LN
229 200
EC2N2AX
230 200
WC2E7DN
231 200
W26LQ
232 200
SW75QL
233 200
SE116PS
234 200
SW31HY
235 200
WC2E7PY
236 200
SE14JW
237 200
SE14PL
238 200
SW59NR
239 200
EC1Y4AG
240 200
SE18XU
241 200
SE12ND
242 200
W148HZ
243 200
SE14XW
244 200
W23XA
245 200
SW35XR
246 200
SE17RJ
247 200
SW75QL
248 200
W1S2FN
249 200
EC1V7LW
250 200
E15EH
251 200
SE115RH
252 200
W1U3BH
253 200
EC1V8DG
254 200
W23QA
255 200
WC2E7HG
256 200
WC1A1PB
257 200
W1K2HP
258 200
SW75ET
259 200
W26JU
260 200
N10EQ
261 200
EC2N1HU
262 200
W113HN
263 200
W84RU
264 200
SE18XU
265 200
NW87LS
266 200
SE13UL
267 200
SE17HT
268 200
N16JB
269 200
SE18XR
270 200
WC2A2AE
271 200
W1D4UG
272 200
SW1H0RH
273 200
NW88QN
274 200
SW1P1GW
275 200
SE12PN
276 200
W1T1RS
277 200
W21SE
278 200
SW75QL
279 200
W1J5ND
280 200
SE164XE
281 200
W1H5EA
282 200
SW1X9JR
283 200
W112RH
284 200
SW1P4QP
285 200
SW72LT
286 200
NW10SB
287 200
E16SE
288 200
W1S3RQ
289 200
EC1V1LH
290 200
W1T4JZ
291 200
SE18SQ
292 200
W1H5FE
293 200
SW40HY
294 200
SW32AQ
295 200
SE18SQ
296 200
NW88JL
297 200
EC1A2AL
298 200
E27NP
299 200
SE17SL
300 200
SW1W8EE
301 200
WC1R4RB
302 200
NW86LS
303 200
W91PS
304 200
W1B1HR
305 200
WC1N2JF
306 200
N16BU
307 200
NW11UN
308 200
SW1P3PA
309 200
E18ZS
310 200
W1S4DZ
311 200
EC1R3BP
312 200
EC1V7ER
313 200
SE115AH
314 200
SW74PB
315 200
W85HY
316 200
W1J7UL
317 200

318 200
WC1H9RW
319 200
SW34NJ
320 200
W84AG
321 200
W86BU
322 200
SW59AS
323 200
E16JE
324 200
W85AD
325 200
SW74QW
326 200
SE10SE
327 200
WC2A1JA
328 200
W1W6XX
329 200
W1F9HT
330 200
SW1Y4EE
331 200
WC2A1PP
332 200
SW32LX
333 200
WC2R
334 404
SW1P1BS
335 200
SW1Y5NG
336 200
SW5
337 404
SW1V2AQ
338 200
SW33DZ
339 200
SW34TX
340 200
W87DB
341 200
W1K7QF
342 200
SW1W9LN
343 200
E18NA
344 200
WC1X0JL
345 200
SW1X9RP
346 200
WC1X9QG
347 200
EC1R1XA
348 200
SE18EE
349 200
SW1X8PA
350 200
W1U2AY
351 200
W22AF
352 200
SW1V1JD
353 200
SW74QB
354 200
SW1P3HA
355 200
SE171RF
356 200
W1U5HR
357 200
E16PX
358 200
WC2A2AE
359 200
SE13JH
360 200
SW36NJ
361 200
W87EJ
362 200
SW1Y4QN
363 200
W1F9QL
364 200
W21JQ
365 200
W24AD
366 200
SW151JP
367 200
W1K2PD
368 200
W1W6DY
369 200
W1T3PQ
370 200
W21NR
371 200
W1T1NT
372 200
SE114SN
373 200
SW72BS
374 200
EC1V9NU
375 200
EC2A4LG
376 200
E27LA
377 200
W1D5NG
378 200
W85LL
379 200
W1J7TD
380 200
WC1E7DB
381 200
W1K7EH
382 200
SW1P2PE
383 200
SE16EB
384 200
NW8
385 404
W1K5AE
386 200
SE114DR
387 200
SE164JR
388 200
W1H5LQ
389 200
W87QA
390 200
W87RW
391 200
SW72BX
392 200
SW1W8SL
393 200
SW1W8QL
394 200
SW1P4HL
395 200
SE18JZ
396 200
SE18HX
397 200
SW1W9BQ
398 200
E144QR
399 200
E10JN
400 200
E149TD
401 200
WC1X8UB
402 200
SE114RS
403 200
WC1V6EA
404 200
E33BB
405 200
E20QP
406 200
E26DL
407 200
E148FQ
408 200
E1W2RP
409 200
E11SE
410 200
E146FU
411 200
SW72BX
412 200
EC2V8BT
413 200
NW17FB
414 200
SW36LP
415 200
N19AG
416 200
SW109PJ
417 200
E13EY
418 200
E26EJ
419 200
E149AN
420 200
W1G8YA
421 200
E32YH
422 200
SW115UF
423 200
W1H6LQ
424 200
E143NQ
425 200
SW36LR
426 200
E33QX
427 200
E14AB
428 200
E147UR
429 200
E3
430 404
W112HF
431 200
NW18QU
432 200
W23NS
433 200
E14
434 404
E32EE
435 200
E10DE
436 200
E1W1PH
437 200
E143EA
438 200
SW8
439 404
E28NU
440 200
NW10NS
441 200
E35LY
442 200
SW64ND
443 200
SW66TA
444 200
E35NH
445 200
E149GL
446 200
SE115TB
447 200
E12DE
448 200
E1W
449 404
W114NN
450 200
E17LA
451 200
E13NU
452 200
E34RQ
453 200
SE116NG
454 200
SW63DR
455 200
E35BS
456 200
E29LH
457 200
SW66SX
458 200
EC1N2HT
459 200
E1W3RY
460 200
E143QB
461 200
E26FG
462 200
SW1P4EN
463 200
EW1
464 404
E149PS
465 200
EC1V0EB
466 200
SW72HW
467 200
N19RY
468 200
E143GL
469 200
SE115HL
470 200
E84DU
471 200
N19BE
472 200
W69BF
473 200
SW10
474 404
W128AY
475 200
SW62UP
476 200
SW152RQ
477 200
E84PN
478 200
W113LN
479 200
E145FU
480 200
W114UE
481 200
WC2R2AB
482 200
SW50TP
483 200
NW17HD
484 200
N16LB
485 200
EC3A7DH
486 200
E14UE
487 200
WC1A2ED
488 200
SE17JB
489 200
SW113LW
490 200
E140NU
491 200
SW184LD
492 200
W148GE
493 200
SW67EX
494 200
E10LA
495 200
E28PP
496 200
SE173SX
497 200
W24XW
498 200
W1J5HE
499 200
E146BP
500 200
E1W2AJ
501 200
SW181AL
502 200
E149US
503 200
E28LT
504 200
EC4A4AD
505 200
W1J9DZ
506 200
W68JT
507 200
SW66BB
508 200
E145NT
509 200
EC3R8AF
510 200
E14FU
511 200
NW19PE
512 200
SW182HY
513 200
W26BB
514 200
E148NS
515 200
W26BB
516 200
W148ES
517 200
E95HR
518 200
SW181EG
519 200
SW113NZ
520 200
E147LY
521 200
W149XA
522 200
NW17AH
523 200
SW112JJ
524 200
SW112
525 404
E84EU
526 200
NW18NP
527 200
E34JS
528 200
W111SA
529 200
SW63JY
530 200
SW112RT
531 200
E142EB
532 200
EC4R1BR
533 200
N10TS
534 200
E20BA
535 200
SE16ER
536 200
SW82TH
537 200
NW14BF
538 200
E15BX
539 200
W120FD
540 200
SW90JQ
541 200
E145JP
542 200
W127FB
543 200
W67DN
544 200
E149PT
545 200
SE19PD
546 200
NW1
547 404
E140AX
548 200
E147TJ
549 200
E14UN
550 200
E12FF
551 200
E34EN

552 200
E28HZ
553 200
N15DT
554 200
W114XX
555 200
E97FA
556 200
E20EA
557 200
E16LY
558 200
E28BW
559 200
E28GN
560 200
E140RZ
561 200
E34QU
562 200
E12BT
563 200
E145AJ
564 200
E27BH
565 200
W60EW
566 200
E20SG
567 200
E34BN
568 200
SW115QX
569 200
SW152LG
570 200
SW63EB
571 200
W113LP
572 200
SW82RS
573 200
E32GT
574 200
SW83JD
575 200
SW115BP
576 200
SW181NS
577 200
SW1E6AL
578 200
SW83QH
579 200
SW63HH
580 200
W140AR
581 200
W69HJ
582 200
SW84DU
583 200
SW61BF
584 200
SW111QF
585 200
SW181JL
586 200
SW181BN
587 200
SW184TH
588 200
SW35NZ
589 200
SW114BD
590 200
SW182SR
591 200
SW112LT
592 200
SE13SX
593 200
SW46QW
594 200
NW10JA
595 200
SW113HL
596 200
W68RL
597 200
W1H1NN
598 200
SW8
599 404
SE10BX
600 200
SW113LY
601 200
SW1H9AH
602 200
EC1A4EE
603 200
SW181PP
604 200
SW152LA
605 200
SW82HL
606 200
SW115RW
607 200
W67LX
608 200
SW113PH
609 200
SW82RW
610 200
EC4V4EG
611 200
E27DT
612 200
W128LQ
613 200
W68NH
614 200
W140PP
615 200
SW152DR
616 200
W148DE
617 200
SW181HE
618 200
W140HJ
619 200
SW66LN
620 200
SW35LX
621 200
SW81QD
622 200
W149BL
623 200
WC2B6LH
624 200
SW65SJ
625 200
E34XY
626 200
SW1P3JY
627 200
E143NX
628 200
E149RT
629 200
E14BS
630 200
W69SY
631 200
NW87AG
632 200
SW64XG
633 200
E148SF
634 200
E15NL
635 200
SW98BJ
636 200
E29JQ
637 200
E34NZ
638 200
E143GL
639 200
E29QH
640 200
N17EB
641 200
E20RR
642 200
N16PZ
643 200
E14RQ
644 200
E14UH
645 200
E34NZ
646 200
E33AA
647 200
EC2Y5EJ
648 200
E146PX
649 200
E33HT
650 200
E1W3DP
651 200
SW62BD
652 200
W67EF
653 200
SW64SG
654 200
SW114PJ
655 200
W114TQ
656 200
SW67SA
657 200
SW100LE
658 200
SW113AS
659 200
E97ND
660 200
SW64BS
661 200
SW114LY
662 200
SW112PF
663 200
SW99BF
664 200
W68HH
665 200
SW151SY
666 200
W149AE
667 200

668 200
W10
669 404
W111JQ
670 200
E84FA
671 200
SE17EH
672 200
W111HF
673 200
E34JU
674 200
W68DX
675 200
E201FQ
676 200
SW100TX
677 200
N12XH
678 200
SW72SL
679 200
SW152SW
680 200
W111RE
681 200
N19QW
682 200
SW82DP
683 200
W60UH
684 200
W149XX
685 200
E32LZ
686 200
E84QU
687 200
E20BY
688 200
SW152SP
689 200
SW67JT
690 200
SW152NA
691 200
SW114LR
692 200
SW181AH
693 200
SW115FH
694 200
E146JR
695 200
E10QW
696 200
SE171RY
697 200
SW112BZ
698 200
SW64HH
699 200
SW62PE
700 200
SW65SA
701 200
SW84DE
702 200
E34RR
703 200
W111EB
704 200
SW36AQ
705 200
SW63SE
706 200
SW49SH
707 200
W114HB
708 200
W68QL
709 200
SW109JT
710 200
SW62GA
711 200
NW16NX
712 200
NW16UL
713 200
SW114EY
714 200
WC2B5DG
715 200
SW100SF
716 200
SW100RS
717 200
SW112LP
718 200
SW152LQ
719 200
SW115AU
720 200
E84EX
721 200
W69JB
722 200
SE12PF
723 200
W114DZ
724 200
W10
725 404
SW62DA
726 200
SW62FR
727 200
W114TX
728 200
SW34ET
729 200
W111NY
730 200
SW100QS
731 200
N15AL
732 200
W1K1PN
733 200
SW112AD
734 200
SW62YB
735 200
EC4Y0BS
736 200
W149BJ
737 200
SW63NR
738 200
SW111NX
739 200
SW111HD
740 200
W67NL
741 200
E201DE
742 200
WC1N1HB
743 200
SW1E6SB
744 200
NW12AE
745 200
SW40RW
746 200
WC1X8QY
747 200
SW21BX
748 200
SW46LE
749 200
SE10HX
750 200
SW81HY
751 200
SW61JY
752 200
NW11EY
753 200
WC1H8BH
754 200
E32PS
755 200
SE19NY
756 200
SW97LZ
757 200
SW118NE
758 200
E152GZ
759 200
E152GZ
760 200
EC4A4AN
761 200
SW118AB
762 200
EC2Y5EJ
763 200
SE115ES
764 200
SW96JJ
765 200
E20
766 404
E148RR
767 200
SW90TP
768 200
SW96AB
769 200
SE17EQ
770 200
SW85BH
771 200
E201JN
772 200
E201GR
773 200
N79AX
774 200
W105TW
775 200
SE19JA
776 200
SE10HX
777 200
E148BG
778 200
WC2A3NA
779 200
N1C4AB
780 200
SW1E5BX
781 200
N1C
782 404
W111AB
783 200
SW99AE
784 200
SE18XR
785 200
SW9
786 404
SW118NY
787 200
SW1A2JH
788 200
EC4Y0HA
789 200
SE167AJ
790 200
SE164DB
791 200

In [121]:
bike_locations.to_csv("bike_locations_postcodes_descriptions.csv")

In [3]:
bike_locations = pd.read_csv("bike_locations_postcodes_descriptions.csv")

*Cleaning scraped data*

In [6]:

bike_locations["description"]=bike_locations["description"].apply(lambda x: x.replace( "[<h3>", ""))
bike_locations["description"]=bike_locations["description"].apply(lambda x: x.replace( "</h3>]", ""))

In [28]:
for i in range(bike_locations.shape[0]):
    bike_locations.at[i, "borough"]=bike_locations.at[i, "description"].split(" in ")[1]
    bike_locations.at[i, "description"] = bike_locations.at[i, "description"].split(" in ")[0]

In [27]:
bike_locations.head()

,Unnamed: 0,ID,commonName,lat,lon,TerminalName,Installed,Locked,InstallDate,RemovalDate,Temporary,NbBikes,NbEmptyDocks,NbDocks,borough,postcode,description
0,0,195,"Milroy Walk, South Bank",51.507244,-0.106237,959,True,False,1.280000e+12,NaN,False,5,25,30,Lambeth,SE1 9NN,a primarily residential postcode
1,1,194,"Hop Exchange, The Borough",51.504627,-0.091773,960,True,False,1.280000e+12,NaN,False,18,38,56,Southwark,SE1 1XF,a primarily non-residential postcode
2,2,196,"Union Street, The Borough",51.503688,-0.098497,961,True,False,1.280000e+12,NaN,False,10,7,17,Southwark,SE1 0LN,a non-residential postcode
3,3,197,"Stamford Street, South Bank",51.505569,-0.111606,962,True,False,1.280000e+12,NaN,False,21,6,27,Lambeth,SE1 9NQ,a mixed residential and non-residential postcode
4,4,193,"Bankside Mix, Bankside",51.505817,-0.100186,963,True,False,1.280000e+12,NaN,False,46,14,60,Southwark,SE1 0HX,a non-residential postcode

In [29]:
bike_locations.description.value_counts()

a residential postcode                              210
a non-residential postcode                          142
a mixed residential and non-residential postcode    138
a primarily residential postcode                    128
a postcode                                           66
a large user postcode                                59
[]                                                   24
a primarily non-residential postcode                 16
a defunct postcode                                    5
a defunct large user postcode                         4
Name: description, dtype: int64

In [36]:
def clean_descriptions(x):
    new = ""
    if x == "a residential postcode":
        new = "R"
    elif x == "a non-residential postcode":
        new = "NR"
    elif x =="a mixed residential and non-residential postcode":
        new = "M"
    elif x == "a primarily residential postcode":
        new = "PR"
    elif x == "a primarily non-residential postcode":
        new = "PNR"
    elif x ==  "a large user postcode":
        new = "LU"
    elif x == "a defunct large user postcode":
        new = "LU"
    else:
        new = "U"
    return new

In [37]:
bike_locations["description_code"]=bike_locations["description"].apply(clean_descriptions)

In [38]:
bike_locations["description_code"].value_counts()

R      210
NR     142
M      138
PR     128
U       95
LU      63
PNR     16
Name: description_code, dtype: int64

In [39]:
bike_locations = bike_locations.drop("description", axis = 1)
bike_locations=bike_locations.drop("TerminalName",axis=1)
bike_locations = bike_locations.drop(["Unnamed: 0", "NbBikes", "NbEmptyDocks","InstallDate",
                                      "Installed", "Locked", "RemovalDate", "Temporary"], axis = 1)

In [47]:
bike_locations.to_csv("bike_locations_clean.csv", index=False)

In [88]:
bike_locations = pd.read_csv("bike_locations_clean.csv")

# Merging data from SQL which contains more local information for each bike dock using data from the UK census

*Data import and combining*

In [89]:
bike_locations_e = pd.read_csv("bike_locations_e.csv")
bike_locations_ec = pd.read_csv("bike_locations_ec.csv")
bike_locations_n = pd.read_csv("bike_locations_n.csv")
bike_locations_nw = pd.read_csv("bike_locations_nw.csv")
bike_locations_sw = pd.read_csv("bike_locations_sw.csv")
bike_locations_se = pd.read_csv("bike_locations_se.csv")
bike_locations_wc = pd.read_csv("bike_locations_wc.csv")
bike_locations_w = pd.read_csv("bike_locations_w.csv")

In [90]:
bike_filled = pd.concat([bike_locations_e, bike_locations_ec,bike_locations_n, bike_locations_nw,bike_locations_sw, bike_locations_se,bike_locations_wc, bike_locations_w])

*Data exploration and cleaning*

In [96]:
bike_filled.columns = ['Dock_ID', 'commonName', 'latitude', 'longitude', 'NbDocks', 'borough',
       'postcode', 'description_code', 'pcd', 'pcd2', 'pcds', 'dointr',
       'doterm', 'usertype', 'oseast1m', 'osnrth1m', 'osgrdind', 'oa11', 'cty',
       'ced', 'laua', 'ward', 'hlthau', 'nhser', 'ctry', 'rgn', 'pcon', 'eer',
       'teclec', 'ttwa', 'pct', 'nuts', 'park', 'lsoa11', 'msoa11', 'wz11',
       'ccg', 'bua11', 'buasd11', 'ru11ind', 'oac11', 'lat', 'long', 'lep1',
       'lep2', 'pfa', 'imd', 'calncv', 'stp']

In [91]:
bike_locations.columns = ['Dock_ID', 'commonName', 'latitude', 'longitude', 'NbDocks', 'borough', 'postcode',
       'description_code']

In [97]:
bike_locations = pd.merge(bike_locations, bike_filled, on="Dock_ID", how="left")

*Dropping many columns after checking number of unique values and meaning*

In [151]:
bike_locations = bike_locations.drop(['commonName_y',
       'latitude_y', 'longitude_y', 'NbDocks_y', 'borough_y', 'postcode_y',
       'description_code_y'], axis=1)
bike_locations=bike_locations.drop(['pcd', 'pcd2', 'pcds'], axis=1)
bike_locations=bike_locations.drop(["dointr", "doterm", "usertype", 'oseast1m', 'osnrth1m', 'osgrdind', "cty", "ced",
                                    "hlthau","nhser", "ctry", "rgn", "eer", "ttwa", "park", "bua11", "ru11ind",
                                    'lat', 'long', "lep1", "lep2"], axis=1)
bike_locations=bike_locations.drop(["teclec", "pfa", "imd", "stp", "calncv"], axis=1)
bike_locations=bike_locations.drop(["pcon", "ccg", "buasd11"], axis=1)

In [152]:
bike_locations.columns

Index(['Dock_ID', 'commonName_x', 'latitude_x', 'longitude_x', 'NbDocks_x',
       'borough_x', 'postcode_x', 'description_code_x', 'oa11', 'laua', 'ward',
       'pct', 'nuts', 'lsoa11', 'msoa11', 'wz11', 'oac11'],
      dtype='object')

In [153]:
bike_locations.to_csv("bike_locations_extra.csv", index=False)

In [2]:
bike_locations=pd.read_csv("bike_locations_extra.csv")
bike_locations

,Dock_ID,commonName_x,latitude_x,longitude_x,NbDocks_x,borough_x,postcode_x,description_code_x,oa11,laua,ward,pct,nuts,lsoa11,msoa11,wz11,oac11
0,449,"Shadwell Station, Shadwell",51.511088,-0.057159,35,Tower Hamlets,E1 0DE,PR,E00021649,E09000030,E05009332,E16000011,E05009332,E01004301,E02000888,E33036294,3B2
1,483,"Albert Gardens, Stepney",51.513280,-0.047784,33,Tower Hamlets,E1 0JN,PR,E00021665,E09000030,E05009332,E16000011,E05009332,E01004305,E02000885,E33036283,3B2
2,464,"St. Mary & St. Michael Church, Stepney",51.514170,-0.052099,25,Tower Hamlets,E1 0LA,M,E00021593,E09000030,E05009334,E16000011,E05009334,E01004287,E02000879,E33036252,3B2
3,715,"Aylward Street, Stepney",51.515630,-0.049067,22,Tower Hamlets,E1 0QW,PR,E00021592,E09000030,E05009334,E16000011,E05009334,E01004289,E02000879,E33036252,3A1
4,282,"Royal London Hospital, Whitechapel",51.518675,-0.061110,42,"Tower Hamlets, Tower Hamlets",E1 1BB,LU,E00021761,E09000030,E05009336,E16000011,E05009336,E01004322,E02000880,E33030694,2B2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
787,79,"Arundel Street, Temple",51.511726,-0.113855,18,London,WC2R 3DX,U,E00023930,E09000033,E05000644,E16000057,E05000644,E01004735,E02000977,E33030971,2B2
788,174,"Strand, Strand",51.512529,-0.115163,36,Westminster,WC2R 1EA,NR,E00023930,E09000033,E05000644,E16000057,E05000644,E01004735,E02000977,E33030974,2B2
789,564,"Somerset House, Strand",51.509943,-0.117619,41,Westminster,WC2R 2AB,NR,E00023930,E09000033,E05000644,E16000057,E05000644,E01004735,E02000977,E33030991,2B2
790,87,"Devonshire Square, Liverpool Street",51.516468,-0.079684,16,London,EC2M 4UJ,U,E00166755,E09000001,E05009292,E16000010,E05009292,E01032739,E02000001,E33031485,2D3
791,789,"Podium, Queen Elizabeth Olympic Park",51.538718,-0.011889,40,London Borough of Newham,E15 2DU,U,E00167200,E09000030,E05009319,E16000011,E05009319,E01004224,E02000864,E33036179,2B2

# Adding information about altitude above sea level from Google Elevation API

In [3]:
import requests
bike_locations["elevation"]=""
apikey = "apikey"
base_url = "https://maps.googleapis.com/maps/api/elevation/json"
for i in range(bike_locations.shape[0]):
    lat = bike_locations["latitude_x"][i]
    lng = bike_locations["longitude_x"][i]
    url = base_url+"?locations="+str(lat)+","+str(lng)+"&key="+apikey
    response = requests.get(url)
    bike_locations.at[i, "elevation"] = response.json().get("results")[0].get("elevation")

In [4]:
bike_locations[bike_locations["elevation"]==bike_locations["elevation"].min()]

,Dock_ID,commonName_x,latitude_x,longitude_x,NbDocks_x,borough_x,postcode_x,description_code_x,oa11,laua,ward,pct,nuts,lsoa11,msoa11,wz11,oac11,elevation
339,792,"Blackfriars Road, Southwark",51.505461,-0.10454,42,Southwark,SE1 9NY,U,E00019781,E09000028,E05011095,E16000059,E05011095,E01003934,E02000808,E33030565,3D3,0.89427

# Adding information about nearest bus, tube and train stops from TFL API

In [7]:
url="https://api.tfl.gov.uk/StopPoint?radius=200&stopTypes=NaptanBusCoachStation,NaptanPublicBusCoachTram&lat=51.5267869&lon=-0.1072012"

In [8]:
response = requests.get(url)

In [9]:
response.status_code

200

In [10]:
#testing result from API
response.json()["stopPoints"][0]["distance"]

20.589285862752423

In [19]:
#setting up a loop to find the nearest bus stops
import time
bike_locations["nearest_bus"]=""
print (bike_locations.shape[0])
for i in range(bike_locations.shape[0]):
    lat=str(bike_locations.at[i, "latitude_x"])
    lon=str(bike_locations.at[i, "longitude_x"])
    url="https://api.tfl.gov.uk/StopPoint?radius=200&stopTypes=NaptanBusCoachStation,NaptanPublicBusCoachTram&lat="+lat+"&lon="+lon+"&app_key="+app_key
    response = requests.get(url)
    try:
        bike_locations.at[i, "nearest_bus"]=response.json()["stopPoints"][0]["distance"]
    except IndexError:
        url="https://api.tfl.gov.uk/StopPoint?radius=500&stopTypes=NaptanBusCoachStation,NaptanPublicBusCoachTram&lat="+lat+"&lon="+lon+"&app_key="+app_key
        response = requests.get(url)
        try:
            bike_locations.at[i, "nearest_bus"]=response.json()["stopPoints"][0]["distance"]
        except IndexError:
            bike_locations.at[i, "nearest_bus"]="further than 500m"
    print (i, response.status_code)
    time.sleep(0.5)

792
0 200
1 200
2 200
3 200
4 200
5 200
6 200
7 200
8 200
9 200
10 200
11 200
12 200
13 200
14 200
15 200
16 200
17 200
18 200
19 200
20 200
21 200
22 200
23 200
24 200
25 200
26 200
27 200
28 200
29 200
30 200
31 200
32 200
33 200
34 200
35 200
36 200
37 200
38 200
39 200
40 200
41 200
42 200
43 200
44 200
45 200
46 200
47 200
48 200
49 200
50 200
51 200
52 200
53 200
54 200
55 200
56 200
57 200
58 200
59 200
60 200
61 200
62 200
63 200
64 200
65 200
66 200
67 200
68 200
69 200
70 200
71 200
72 200
73 200
74 200
75 200
76 200
77 200
78 200
79 200
80 200
81 200
82 200
83 200
84 200
85 200
86 200
87 200
88 200
89 200
90 200
91 200
92 200
93 200
94 200
95 200
96 200
97 200
98 200
99 200
100 200
101 200
102 200
103 200
104 200
105 200
106 200
107 200
108 200
109 200
110 200
111 200
112 200
113 200
114 200
115 200
116 200
117 200
118 200
119 200
120 200
121 200
122 200
123 200
124 200
125 200
126 200
127 200
128 200
129 200
130 200
131 200
132 200
133 200
134 200
135 200
136 200
137 200
138 200
139 200
140 200
141 200
142 200
143 200
144 200
145 200
146 200
147 200
148 200
149 200
150 200
151 200
152 200
153 200
154 200
155 200
156 200
157 200
158 200
159 200
160 200
161 200
162 200
163 200
164 200
165 200
166 200
167 200
168 200
169 200
170 200
171 200
172 200
173 200
174 200
175 200
176 200
177 200
178 200
179 200
180 200
181 200
182 200
183 200
184 200
185 200
186 200
187 200
188 200
189 200
190 200
191 200
192 200
193 200
194 200
195 200
196 200
197 200
198 200
199 200
200 200
201 200
202 200
203 200
204 200
205 200
206 200
207 200
208 200
209 200
210 200
211 200
212 200
213 200
214 200
215 200
216 200
217 200
218 200
219 200
220 200
221 200
222 200
223 200
224 200
225 200
226 200
227 200
228 200
229 200
230 200
231 200
232 200
233 200
234 200
235 200
236 200
237 200
238 200
239 200
240 200
241 200
242 200
243 200
244 200
245 200
246 200
247 200
248 200
249 200
250 200
251 200
252 200
253 200
254 200
255 200
256 200
257 200
258 200
259 200
260 200
261 200
262 200
263 200
264 200
265 200
266 200
267 200
268 200
269 200
270 200
271 200
272 200
273 200
274 200
275 200
276 200
277 200
278 200
279 200
280 200
281 200
282 200
283 200
284 200
285 200
286 200
287 200
288 200
289 200
290 200
291 200
292 200
293 200
294 200
295 200
296 200
297 200
298 200
299 200
300 200
301 200
302 200
303 200
304 200
305 200
306 200
307 200
308 200
309 200
310 200
311 200
312 200
313 200
314 200
315 200
316 200
317 200
318 200
319 200
320 200
321 200
322 200
323 200
324 200
325 200
326 200
327 200
328 200
329 200
330 200
331 200
332 200
333 200
334 200
335 200
336 200
337 200
338 200
339 200
340 200
341 200
342 200
343 200
344 200
345 200
346 200
347 200
348 200
349 200
350 200
351 200
352 200
353 200
354 200
355 200
356 200
357 200
358 200
359 200
360 200
361 200
362 200
363 200
364 200
365 200
366 200
367 200
368 200
369 200
370 200
371 200
372 200
373 200
374 200
375 200
376 200
377 200
378 200
379 200
380 200
381 200
382 200
383 200
384 200
385 200
386 200
387 200
388 200
389 200
390 200
391 200
392 200
393 200
394 200
395 200
396 200
397 200
398 200
399 200
400 200
401 200
402 200
403 200
404 200
405 200
406 200
407 200
408 200
409 200
410 200
411 200
412 200
413 200
414 200
415 200
416 200
417 200
418 200
419 200
420 200
421 200
422 200
423 200
424 200
425 200
426 200
427 200
428 200
429 200
430 200
431 200
432 200
433 200
434 200
435 200
436 200
437 200
438 200
439 200
440 200
441 200
442 200
443 200
444 200
445 200
446 200
447 200
448 200
449 200
450 200
451 200
452 200
453 200
454 200
455 200
456 200
457 200
458 200
459 200
460 200
461 200
462 200
463 200
464 200
465 200
466 200
467 200
468 200
469 200
470 200
471 200
472 200
473 200
474 200
475 200
476 200
477 200
478 200
479 200
480 200
481 200
482 200
483 200
484 200
485 200
486 200
487 200
488 200
489 200
490 200
491 200
492 200
493 200
494 200
495 200
496 200
497 200
498 200
499 200
500 200
501 200
502 200
503 200
504 200
505 200
506 200
507 200
508 200
509 200
510 200
511 200
512 200
513 200
514 200
515 200
516 200
517 200
518 200
519 200
520 200
521 200
522 200
523 200
524 200
525 200
526 200
527 200
528 200
529 200
530 200
531 200
532 200
533 200
534 200
535 200
536 200
537 200
538 200
539 200
540 200
541 200
542 200
543 200
544 200
545 200
546 200
547 200
548 200
549 200
550 200
551 200
552 200
553 200
554 200
555 200
556 200
557 200
558 200
559 200
560 200
561 200
562 200
563 200
564 200
565 200
566 200
567 200
568 200
569 200
570 200
571 200
572 200
573 200
574 200
575 200
576 200
577 200
578 200
579 200
580 200
581 200
582 200
583 200
584 200
585 200
586 200
587 200
588 200
589 200
590 200
591 200
592 200
593 200
594 200
595 200
596 200
597 200
598 200
599 200
600 200
601 200
602 200
603 200
604 200
605 200
606 200
607 200
608 200
609 200
610 200
611 200
612 200
613 200
614 200
615 200
616 200
617 200
618 200
619 200
620 200
621 200
622 200
623 200
624 200
625 200
626 200
627 200
628 200
629 200
630 200
631 200
632 200
633 200
634 200
635 200
636 200
637 200
638 200
639 200
640 200
641 200
642 200
643 200
644 200
645 200
646 200
647 200
648 200
649 200
650 200
651 200
652 200
653 200
654 200
655 200
656 200
657 200
658 200
659 200
660 200
661 200
662 200
663 200
664 200
665 200
666 200
667 200
668 200
669 200
670 200
671 200
672 200
673 200
674 200
675 200
676 200
677 200
678 200
679 200
680 200
681 200
682 200
683 200
684 200
685 200
686 200
687 200
688 200
689 200
690 200
691 200
692 200
693 200
694 200
695 200
696 200
697 200
698 200
699 200
700 200
701 200
702 200
703 200
704 200
705 200
706 200
707 200
708 200
709 200
710 200
711 200
712 200
713 200
714 200
715 200
716 200
717 200
718 200
719 200
720 200
721 200
722 200
723 200
724 200
725 200
726 200
727 200
728 200
729 200
730 200
731 200
732 200
733 200
734 200
735 200
736 200
737 200
738 200
739 200
740 200
741 200
742 200
743 200
744 200
745 200
746 200
747 200
748 200
749 200
750 200
751 200
752 200
753 200
754 200
755 200
756 200
757 200
758 200
759 200
760 200
761 200
762 200
763 200
764 200
765 200
766 200
767 200
768 200
769 200
770 200
771 200
772 200
773 200
774 200
775 200
776 200
777 200
778 200
779 200
780 200
781 200
782 200
783 200
784 200
785 200
786 200
787 200
788 200
789 200
790 200
791 200

In [21]:
#loop to find the nearest tube stations
bike_locations["nearest_tube"]=""
print (bike_locations.shape[0])
for i in range(bike_locations.shape[0]):
    lat=str(bike_locations.at[i, "latitude_x"])
    lon=str(bike_locations.at[i, "longitude_x"])
    url="https://api.tfl.gov.uk/StopPoint?radius=500&stopTypes=NaptanMetroStation&lat="+lat+"&lon="+lon+"&app_key="+app_key
    response = requests.get(url)
    try:
        bike_locations.at[i, "nearest_tube"]=response.json()["stopPoints"][0]["distance"]
    except IndexError:
        url="https://api.tfl.gov.uk/StopPoint?radius=1000&stopTypes=NaptanMetroStation&lat="+lat+"&lon="+lon+"&app_key="+app_key
        response = requests.get(url)
        try:
            bike_locations.at[i, "nearest_tube"]=response.json()["stopPoints"][0]["distance"]
        except IndexError:
            bike_locations.at[i, "nearest_tube"]="further than 1km"
    print (i, response.status_code)
    time.sleep(0.4)

792
0 200
1 200
2 200
3 200
4 200
5 200
6 200
7 200
8 200
9 200
10 200
11 200
12 200
13 200
14 200
15 200
16 200
17 200
18 200
19 200
20 200
21 200
22 200
23 200
24 200
25 200
26 200
27 200
28 200
29 200
30 200
31 200
32 200
33 200
34 200
35 200
36 200
37 200
38 200
39 200
40 200
41 200
42 200
43 200
44 200
45 200
46 200
47 200
48 200
49 200
50 200
51 200
52 200
53 200
54 200
55 200
56 200
57 200
58 200
59 200
60 200
61 200
62 200
63 200
64 200
65 200
66 200
67 200
68 200
69 200
70 200
71 200
72 200
73 200
74 200
75 200
76 200
77 200
78 200
79 200
80 200
81 200
82 200
83 200
84 200
85 200
86 200
87 200
88 200
89 200
90 200
91 200
92 200
93 200
94 200
95 200
96 200
97 200
98 200
99 200
100 200
101 200
102 200
103 200
104 200
105 200
106 200
107 200
108 200
109 200
110 200
111 200
112 200
113 200
114 200
115 200
116 200
117 200
118 200
119 200
120 200
121 200
122 200
123 200
124 200
125 200
126 200
127 200
128 200
129 200
130 200
131 200
132 200
133 200
134 200
135 200
136 200
137 200
138 200
139 200
140 200
141 200
142 200
143 200
144 200
145 200
146 200
147 200
148 200
149 200
150 200
151 200
152 200
153 200
154 200
155 200
156 200
157 200
158 200
159 200
160 200
161 200
162 200
163 200
164 200
165 200
166 200
167 200
168 200
169 200
170 200
171 200
172 200
173 200
174 200
175 200
176 200
177 200
178 200
179 200
180 200
181 200
182 200
183 200
184 200
185 200
186 200
187 200
188 200
189 200
190 200
191 200
192 200
193 200
194 200
195 200
196 200
197 200
198 200
199 200
200 200
201 200
202 200
203 200
204 200
205 200
206 200
207 200
208 200
209 200
210 200
211 200
212 200
213 200
214 200
215 200
216 200
217 200
218 200
219 200
220 200
221 200
222 200
223 200
224 200
225 200
226 200
227 200
228 200
229 200
230 200
231 200
232 200
233 200
234 200
235 200
236 200
237 200
238 200
239 200
240 200
241 200
242 200
243 200
244 200
245 200
246 200
247 200
248 200
249 200
250 200
251 200
252 200
253 200
254 200
255 200
256 200
257 200
258 200
259 200
260 200
261 200
262 200
263 200
264 200
265 200
266 200
267 200
268 200
269 200
270 200
271 200
272 200
273 200
274 200
275 200
276 200
277 200
278 200
279 200
280 200
281 200
282 200
283 200
284 200
285 200
286 200
287 200
288 200
289 200
290 200
291 200
292 200
293 200
294 200
295 200
296 200
297 200
298 200
299 200
300 200
301 200
302 200
303 200
304 200
305 200
306 200
307 200
308 200
309 200
310 200
311 200
312 200
313 200
314 200
315 200
316 200
317 200
318 200
319 200
320 200
321 200
322 200
323 200
324 200
325 200
326 200
327 200
328 200
329 200
330 200
331 200
332 200
333 200
334 200
335 200
336 200
337 200
338 200
339 200
340 200
341 200
342 200
343 200
344 200
345 200
346 200
347 200
348 200
349 200
350 200
351 200
352 200
353 200
354 200
355 200
356 200
357 200
358 200
359 200
360 200
361 200
362 200
363 200
364 200
365 200
366 200
367 200
368 200
369 200
370 200
371 200
372 200
373 200
374 200
375 200
376 200
377 200
378 200
379 200
380 200
381 200
382 200
383 200
384 200
385 200
386 200
387 200
388 200
389 200
390 200
391 200
392 200
393 200
394 200
395 200
396 200
397 200
398 200
399 200
400 200
401 200
402 200
403 200
404 200
405 200
406 200
407 200
408 200
409 200
410 200
411 200
412 200
413 200
414 200
415 200
416 200
417 200
418 200
419 200
420 200
421 200
422 200
423 200
424 200
425 200
426 200
427 200
428 200
429 200
430 200
431 200
432 200
433 200
434 200
435 200
436 200
437 200
438 200
439 200
440 200
441 200
442 200
443 200
444 200
445 200
446 200
447 200
448 200
449 200
450 200
451 200
452 200
453 200
454 200
455 200
456 200
457 200
458 200
459 200
460 200
461 200
462 200
463 200
464 200
465 200
466 200
467 200
468 200
469 200
470 200
471 200
472 200
473 200
474 200
475 200
476 200
477 200
478 200
479 200
480 200
481 200
482 200
483 200
484 200
485 200
486 200
487 200
488 200
489 200
490 200
491 200
492 200
493 200
494 200
495 200
496 200
497 200
498 200
499 200
500 200
501 200
502 200
503 200
504 200
505 200
506 200
507 200
508 200
509 200
510 200
511 200
512 200
513 200
514 200
515 200
516 200
517 200
518 200
519 200
520 200
521 200
522 200
523 200
524 200
525 200
526 200
527 200
528 200
529 200
530 200
531 200
532 200
533 200
534 200
535 200
536 200
537 200
538 200
539 200
540 200
541 200
542 200
543 200
544 200
545 200
546 200
547 200
548 200
549 200
550 200
551 200
552 200
553 200
554 200
555 200
556 200
557 200
558 200
559 200
560 200
561 200
562 200
563 200
564 200
565 200
566 200
567 200
568 200
569 200
570 200
571 200
572 200
573 200
574 200
575 200
576 200
577 200
578 200
579 200
580 200
581 200
582 200
583 200
584 200
585 200
586 200
587 200
588 200
589 200
590 200
591 200
592 200
593 200
594 200
595 200
596 200
597 200
598 200
599 200
600 200
601 200
602 200
603 200
604 200
605 200
606 200
607 200
608 200
609 200
610 200
611 200
612 200
613 200
614 200
615 200
616 200
617 200
618 200
619 200
620 200
621 200
622 200
623 200
624 200
625 200
626 200
627 200
628 200
629 200
630 200
631 200
632 200
633 200
634 200
635 200
636 200
637 200
638 200
639 200
640 200
641 200
642 200
643 200
644 200
645 200
646 200
647 200
648 200
649 200
650 200
651 200
652 200
653 200
654 200
655 200
656 200
657 200
658 200
659 200
660 200
661 200
662 200
663 200
664 200
665 200
666 200
667 200
668 200
669 200
670 200
671 200
672 200
673 200
674 200
675 200
676 200
677 200
678 200
679 200
680 200
681 200
682 200
683 200
684 200
685 200
686 200
687 200
688 200
689 200
690 200
691 200
692 200
693 200
694 200
695 200
696 200
697 200
698 200
699 200
700 200
701 200
702 200
703 200
704 200
705 200
706 200
707 200
708 200
709 200
710 200
711 200
712 200
713 200
714 200
715 200
716 200
717 200
718 200
719 200
720 200
721 200
722 200
723 200
724 200
725 200
726 200
727 200
728 200
729 200
730 200
731 200
732 200
733 200
734 200
735 200
736 200
737 200
738 200
739 200
740 200
741 200
742 200
743 200
744 200
745 200
746 200
747 200
748 200
749 200
750 200
751 200
752 200
753 200
754 200
755 200
756 200
757 200
758 200
759 200
760 200
761 200
762 200
763 200
764 200
765 200
766 200
767 200
768 200
769 200
770 200
771 200
772 200
773 200
774 200
775 200
776 200
777 200
778 200
779 200
780 200
781 200
782 200
783 200
784 200
785 200
786 200
787 200
788 200
789 200
790 200
791 200

In [22]:
# loop to find nearest railway station
bike_locations["nearest_rail"]=""

print (bike_locations.shape[0])
for i in range(bike_locations.shape[0]):
    lat=str(bike_locations.at[i, "latitude_x"])
    lon=str(bike_locations.at[i, "longitude_x"])
    url="https://api.tfl.gov.uk/StopPoint?radius=500&stopTypes=NaptanRailStation&lat="+lat+"&lon="+lon+"&app_key="+app_key
    response = requests.get(url)
    try:
        bike_locations.at[i, "nearest_rail"]=response.json()["stopPoints"][0]["distance"]
    except IndexError:
        url="https://api.tfl.gov.uk/StopPoint?radius=1000&stopTypes=NaptanRailStation&lat="+lat+"&lon="+lon+"&app_key="+app_key
        response = requests.get(url)
        try:
            bike_locations.at[i, "nearest_rail"]=response.json()["stopPoints"][0]["distance"]
        except IndexError:
            bike_locations.at[i, "nearest_rail"]="further than 1km"
    print (i, response.status_code)
    time.sleep(0.4)

792
0 200
1 200
2 200
3 200
4 200
5 200
6 200
7 200
8 200
9 200
10 200
11 200
12 200
13 200
14 200
15 200
16 200
17 200
18 200
19 200
20 200
21 200
22 200
23 200
24 200
25 200
26 200
27 200
28 200
29 200
30 200
31 200
32 200
33 200
34 200
35 200
36 200
37 200
38 200
39 200
40 200
41 200
42 200
43 200
44 200
45 200
46 200
47 200
48 200
49 200
50 200
51 200
52 200
53 200
54 200
55 200
56 200
57 200
58 200
59 200
60 200
61 200
62 200
63 200
64 200
65 200
66 200
67 200
68 200
69 200
70 200
71 200
72 200
73 200
74 200
75 200
76 200
77 200
78 200
79 200
80 200
81 200
82 200
83 200
84 200
85 200
86 200
87 200
88 200
89 200
90 200
91 200
92 200
93 200
94 200
95 200
96 200
97 200
98 200
99 200
100 200
101 200
102 200
103 200
104 200
105 200
106 200
107 200
108 200
109 200
110 200
111 200
112 200
113 200
114 200
115 200
116 200
117 200
118 200
119 200
120 200
121 200
122 200
123 200
124 200
125 200
126 200
127 200
128 200
129 200
130 200
131 200
132 200
133 200
134 200
135 200
136 200
137 200
138 200
139 200
140 200
141 200
142 200
143 200
144 200
145 200
146 200
147 200
148 200
149 200
150 200
151 200
152 200
153 200
154 200
155 200
156 200
157 200
158 200
159 200
160 200
161 200
162 200
163 200
164 200
165 200
166 200
167 200
168 200
169 200
170 200
171 200
172 200
173 200
174 200
175 200
176 200
177 200
178 200
179 200
180 200
181 200
182 200
183 200
184 200
185 200
186 200
187 200
188 200
189 200
190 200
191 200
192 200
193 200
194 200
195 200
196 200
197 200
198 200
199 200
200 200
201 200
202 200
203 200
204 200
205 200
206 200
207 200
208 200
209 200
210 200
211 200
212 200
213 200
214 200
215 200
216 200
217 200
218 200
219 200
220 200
221 200
222 200
223 200
224 200
225 200
226 200
227 200
228 200
229 200
230 200
231 200
232 200
233 200
234 200
235 200
236 200
237 200
238 200
239 200
240 200
241 200
242 200
243 200
244 200
245 200
246 200
247 200
248 200
249 200
250 200
251 200
252 200
253 200
254 200
255 200
256 200
257 200
258 200
259 200
260 200
261 200
262 200
263 200
264 200
265 200
266 200
267 200
268 200
269 200
270 200
271 200
272 200
273 200
274 200
275 200
276 200
277 200
278 200
279 200
280 200
281 200
282 200
283 200
284 200
285 200
286 200
287 200
288 200
289 200
290 200
291 200
292 200
293 200
294 200
295 200
296 200
297 200
298 200
299 200
300 200
301 200
302 200
303 200
304 200
305 200
306 200
307 200
308 200
309 200
310 200
311 200
312 200
313 200
314 200
315 200
316 200
317 200
318 200
319 200
320 200
321 200
322 200
323 200
324 200
325 200
326 200
327 200
328 200
329 200
330 200
331 200
332 200
333 200
334 200
335 200
336 200
337 200
338 200
339 200
340 200
341 200
342 200
343 200
344 200
345 200
346 200
347 200
348 200
349 200
350 200
351 200
352 200
353 200
354 200
355 200
356 200
357 200
358 200
359 200
360 200
361 200
362 200
363 200
364 200
365 200
366 200
367 200
368 200
369 200
370 200
371 200
372 200
373 200
374 200
375 200
376 200
377 200
378 200
379 200
380 200
381 200
382 200
383 200
384 200
385 200
386 200
387 200
388 200
389 200
390 200
391 200
392 200
393 200
394 200
395 200
396 200
397 200
398 200
399 200
400 200
401 200
402 200
403 200
404 200
405 200
406 200
407 200
408 200
409 200
410 200
411 200
412 200
413 200
414 200
415 200
416 200
417 200
418 200
419 200
420 200
421 200
422 200
423 200
424 200
425 200
426 200
427 200
428 200
429 200
430 200
431 200
432 200
433 200
434 200
435 200
436 200
437 200
438 200
439 200
440 200
441 200
442 200
443 200
444 200
445 200
446 200
447 200
448 200
449 200
450 200
451 200
452 200
453 200
454 200
455 200
456 200
457 200
458 200
459 200
460 200
461 200
462 200
463 200
464 200
465 200
466 200
467 200
468 200
469 200
470 200
471 200
472 200
473 200
474 200
475 200
476 200
477 200
478 200
479 200
480 200
481 200
482 200
483 200
484 200
485 200
486 200
487 200
488 200
489 200
490 200
491 200
492 200
493 200
494 200
495 200
496 200
497 200
498 200
499 200
500 200
501 200
502 200
503 200
504 200
505 200
506 200
507 200
508 200
509 200
510 200
511 200
512 200
513 200
514 200
515 200
516 200
517 200
518 200
519 200
520 200
521 200
522 200
523 200
524 200
525 200
526 200
527 200
528 200
529 200
530 200
531 200
532 200
533 200
534 200
535 200
536 200
537 200
538 200
539 200
540 200
541 200
542 200
543 200
544 200
545 200
546 200
547 200
548 200
549 200
550 200
551 200
552 200
553 200
554 200
555 200
556 200
557 200
558 200
559 200
560 200
561 200
562 200
563 200
564 200
565 200
566 200
567 200
568 200
569 200
570 200
571 200
572 200
573 200
574 200
575 200
576 200
577 200
578 200
579 200
580 200
581 200
582 200
583 200
584 200
585 200
586 200
587 200
588 200
589 200
590 200
591 200
592 200
593 200
594 200
595 200
596 200
597 200
598 200
599 200
600 200
601 200
602 200
603 200
604 200
605 200
606 200
607 200
608 200
609 200
610 200
611 200
612 200
613 200
614 200
615 200
616 200
617 200
618 200
619 200
620 200
621 200
622 200
623 200
624 200
625 200
626 200
627 200
628 200
629 200
630 200
631 200
632 200
633 200
634 200
635 200
636 200
637 200
638 200
639 200
640 200
641 200
642 200
643 200
644 200
645 200
646 200
647 200
648 200
649 200
650 200
651 200
652 200
653 200
654 200
655 200
656 200
657 200
658 200
659 200
660 200
661 200
662 200
663 200
664 200
665 200
666 200
667 200
668 200
669 200
670 200
671 200
672 200
673 200
674 200
675 200
676 200
677 200
678 200
679 200
680 200
681 200
682 200
683 200
684 200
685 200
686 200
687 200
688 200
689 200
690 200
691 200
692 200
693 200
694 200
695 200
696 200
697 200
698 200
699 200
700 200
701 200
702 200
703 200
704 200
705 200
706 200
707 200
708 200
709 200
710 200
711 200
712 200
713 200
714 200
715 200
716 200
717 200
718 200
719 200
720 200
721 200
722 200
723 200
724 200
725 200
726 200
727 200
728 200
729 200
730 200
731 200
732 200
733 200
734 200
735 200
736 200
737 200
738 200
739 200
740 200
741 200
742 200
743 200
744 200
745 200
746 200
747 200
748 200
749 200
750 200
751 200
752 200
753 200
754 200
755 200
756 200
757 200
758 200
759 200
760 200
761 200
762 200
763 200
764 200
765 200
766 200
767 200
768 200
769 200
770 200
771 200
772 200
773 200
774 200
775 200
776 200
777 200
778 200
779 200
780 200
781 200
782 200
783 200
784 200
785 200
786 200
787 200
788 200
789 200
790 200
791 200

In [55]:
bike_locations['nearest_rail']=bike_locations['nearest_rail'].astype(float)

*rerunning loop for docks that were too far away from a station. The larger the search radius the slower the request hence running it twice*

In [42]:
#adding rail station when the nearest was further than 1km away with increased search radius
for i in range(bike_locations.shape[0]):
    
    if bike_locations.at[i, "nearest_rail"]=="further than 1km":
        lat=str(bike_locations.at[i, "latitude_x"])
        lon=str(bike_locations.at[i, "longitude_x"])
        url="https://api.tfl.gov.uk/StopPoint?radius=2000&stopTypes=NaptanRailStation&lat="+lat+"&lon="+lon+"&app_key="+app_key
        response = requests.get(url)
        try:
            bike_locations.at[i, "nearest_rail"]=response.json()["stopPoints"][0]["distance"]
        except IndexError:
            url="https://api.tfl.gov.uk/StopPoint?radius=3000&stopTypes=NaptanRailStation&lat="+lat+"&lon="+lon+"&app_key="+app_key
            response = requests.get(url)
            try:
                bike_locations.at[i, "nearest_rail"]=response.json()["stopPoints"][0]["distance"]
            except IndexError:
                bike_locations.at[i, "nearest_rail"]="further than 3km"
        print (i, response.status_code)
        time.sleep(0.4)
    else:continue

15 200
34 200
35 200
36 200
37 200
38 200
40 200
41 200
42 200
43 200
45 200
46 200
47 200
48 200
49 200
50 200
51 200
52 200
53 200
58 200
59 200
60 200
61 200
62 200
63 200
64 200
65 200
66 200
67 200
68 200
84 200
106 200
107 200
108 200
111 200
112 200
113 200
114 200
115 200
116 200
117 200
120 200
121 200
122 200
123 200
125 200
126 200
127 200
128 200
149 200
156 200
209 200
210 200
255 200
266 200
270 200
272 200
273 200
274 200
280 200
294 200
360 200
366 200
373 200
385 200
393 200
395 200
413 200
440 200
441 200
456 200
468 200
469 200
470 200
473 200
475 200
482 200
483 200
484 200
485 200
486 200
487 200
488 200
489 200
490 200
491 200
492 200
493 200
494 200
495 200
496 200
497 200
499 200
519 200
520 200
523 200
525 200
526 200
527 200
529 200
530 200
531 200
532 200
533 200
534 200
535 200
537 200
539 200
540 200
541 200
542 200
543 200
544 200
545 200
546 200
547 200
548 200
549 200
550 200
551 200
552 200
553 200
554 200
555 200
556 200
557 200
558 200
561 200
564 200
566 200
575 200
576 200
579 200
583 200
586 200
587 200
588 200
589 200
590 200
591 200
592 200
594 200
595 200
596 200
597 200
598 200
607 200
624 200
625 200
626 200
627 200
632 200
633 200
636 200
637 200
644 200
645 200
646 200
647 200
649 200
650 200
651 200
652 200
653 200
654 200
655 200
656 200
657 200
658 200
659 200
660 200
661 200
663 200
664 200
665 200
666 200
667 200
668 200
671 200
678 200
679 200
687 200
691 200
692 200
693 200
694 200
695 200
696 200
698 200
705 200
706 200
711 200
712 200
713 200
714 200
715 200
717 200
718 200
719 200
720 200
721 200
722 200
723 200
724 200
725 200
727 200
728 200
732 200
733 200
735 200
736 200
738 200
741 200
742 200
743 200
744 200
745 200
746 200
773 200

In [44]:
# adding nearest tube stations for docks where the nearest tube is further than 1km away with increased search radius
print (bike_locations.shape[0])
for i in range(bike_locations.shape[0]):
    if bike_locations.at[i, "nearest_tube"]=="further than 1km":
        lat=str(bike_locations.at[i, "latitude_x"])
        lon=str(bike_locations.at[i, "longitude_x"])
        url="https://api.tfl.gov.uk/StopPoint?radius=1500&stopTypes=NaptanMetroStation&lat="+lat+"&lon="+lon+"&app_key="+app_key
        response = requests.get(url)
        try:
            bike_locations.at[i, "nearest_tube"]=response.json()["stopPoints"][0]["distance"]
        except IndexError:
            url="https://api.tfl.gov.uk/StopPoint?radius=3000&stopTypes=NaptanMetroStation&lat="+lat+"&lon="+lon+"&app_key="+app_key
            response = requests.get(url)
            try:
                bike_locations.at[i, "nearest_tube"]=response.json()["stopPoints"][0]["distance"]
            except IndexError:
                bike_locations.at[i, "nearest_tube"]="further than 3km"
        print (i, response.status_code)
        time.sleep(0.4)

792
90 200
92 200
94 200
95 200
96 200
106 200
128 200
129 200
130 200
131 200
132 200
135 200
136 200
213 200
214 200
255 200
367 200
369 200
373 200
374 200
375 200
376 200
377 200
378 200
379 200
380 200
381 200
382 200
383 200
384 200
385 200
386 200
387 200
388 200
389 200
390 200
391 200
392 200
393 200
394 200
395 200
396 200
397 200
398 200
399 200
400 200
401 200
402 200
404 200
405 200
416 200
417 200
418 200
419 200
421 200
424 200
425 200
426 200
427 200
491 200
492 200
494 200
502 200
515 200
516 200
517 200
521 200
533 200
560 200
571 200
573 200
718 200

# Exporting final version

In [ ]:
bike_locations.to_csv("bike_locations_extra.csv", index=False)